### ISSUE TITLE
Way to temporarily 'redirect' verbs to another verb

### ISSUE THREAD

**Issue by shdwcat** [offalynne/Input#1]
The situation I'm thinking of is nested UI navigation. Imagine we have an in-game menu, and two verbs to go with that menu 'Select' and 'Back'. Now let's say I'm looking at the options menu and I've made some changes, and then I press the Back button. I want to confirm that the user doesn't want to save their changes, so I pop up a dialog over the options menu, asking if the want to save their changes. The dialog is checking the 'Select' verb for Yes and 'Back' verb for No.

The problem is, the options menu is also checking the 'Select' and 'Back' verbs for its own input logic! So what I want is something like:
input_redirect_verb(old_verb, new_verb)

Which, for the above example, I might call like so: input_redirect_verb("Select", "Select_Dialog").

After calling input_redirect_verb a subsequent call to input_check("Select") would no longer return true when whatever real input was mapped to "Select" is pressed. Instead, input_check("Select_Dialog") would return true.

The second part of this would ideally be an input_undo_redirect(current_verb), which would basically reverse whatever old_verb got mapped to current_verb. This is just a nice to have, as I could call input_redirect_verb("Select_Dialog", "Select") myself, but it would be nice for re-usability purposes to not have to keep track of how I got to the current verb mapping (so that a confirmation dialog box could be re-used from anywhere without me tracking the redirections myself).

**Comment by JujuAdams** [comment]
Normally the way you'd handle situations like this is 1) process the dialog first and 2) [consume](https://github.com/JujuAdams/input/wiki/Functions-(Other)#input_consumeverb-playerindex) user input. Is this a viable solution for you?

**Comment by shdwcat** [comment]
> 
> 
> Normally the way you'd handle situations like this is 1) process the dialog first and 2) [consume](https://github.com/JujuAdams/input/wiki/Functions-(Other)#input_consumeverb-playerindex) user input. Is this a viable solution for you?

It's viable though it requires me to keep track of the processing order and somehow ensure that the dialog processing happens centrally somewhere rather than in the step events for each dialog. With this feature, the create event of the dialog could redirect it, the step event processes it, and the clean up event un-redirects it. This keeps the input handling encapsulated to the dialog, without needing to track any state externally.
