### ISSUE TITLE
HTML5 target: error message, and black screen when gamepad used

### ISSUE THREAD

**Issue by modalmodule** [offalynne/Input#105]
![image](https://user-images.githubusercontent.com/75230821/127725133-221d0373-3c5f-41a5-8069-310837f1897d.png)
When testing an html5 game using input, I initially got this error message. Prompted by alynne on the discord (who said html5 wasn't supported but may work anyway), I ignored the message to further test. Keyboard implementation worked fine. I pushed my luck a bit, and tried to test controller support, and having input_default_gamepad_button assigned and having the gamepad plugged in produces a black window where the game should be, regardless of true or false for #macro INPUT_SDL2_REMAPPING and #macro INPUT_SDL2_ALLOW_EXTERNAL of __input_config (any configuration of true and false, tried them all just in case). If I unplug the controller the game loads, or if I comment out the gamepad controls.

**Comment by offalynne** [comment]
We workshopped this a bit in Discord -- controller bindings are crashing `get_binding`. `main` branch is hitting the dynamic `gamepad_device_count` bug fixed naively in #100 (`index out of range`), dev branch is hitting `cannot read property of undefined`, which looks to be the same issue currently crashing Android.

**Comment by JujuAdams** [comment]
Fixed the environment variable problem - on HTML5 that was returning `undefined` and sneaking its way through the initial empty string check <https://github.com/JujuAdams/Input/commit/c4f54228f7ff7e271a35281ca05995105c63cba0>

I found a serious upstream bug with fluent interfaces whereby `(new __input_class_binding()).method()` was returning `undefined`, breaking a number of things when setting default bindings and when rebinding controls. A workaround is now in the project for this bug <https://github.com/JujuAdams/Input/commit/98cfc4d922f26d07b6788fece55e203319efe1bd> <https://github.com/JujuAdams/Input/commit/471cab3782aa49407ff9423766b537aae40c0a99>

Looking at writing a controller VID/PID parser for HTML5 now...

**Comment by JujuAdams** [comment]
mmok, looks like Chrome and Firefox return slightly different descriptions (see `__input_gamepad_set_vid_pid()`) so I'm gonna check Safari too to make sure we're handling that case.

As for dynamic gamepad counts, see #106 (commits https://github.com/JujuAdams/Input/commit/d2c6b298b76e0a94f45852054420e4fb86e92ec3 and https://github.com/JujuAdams/Input/commit/77141ddafa6a54e2ec259037f917bee858de4f80)

**Comment by JujuAdams** [comment]
On Mac, Safari doesn't report VID/PID in the description (no GUID either) and Firefox mangles the VID/PID by clipping off leading zeroes (`054c` -> `54c`, see #107). Chrome seems ok though?

**Comment by JujuAdams** [comment]
See also #107 #109 and maybe #97

**Comment by JujuAdams** [comment]
Testing shows that the original impetus for this ticket has been fixed. More testing on HTML5 needed, but we're largely out of the woods
