### ISSUE TITLE
VID/PID extraction on Firefox MacOS doesn't cope with missing leading zeroes

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#107]
Firefox mangles the VID/PID by clipping off leading zeroes (`054c` -> `54c`) which means Input won't be able to handle SDL remapping. GM's native remapping handles common gamepads ok though so this isn't a particularly important bug to fix

**Comment by offalynne** [comment]
I suspect it isn’t GM but is in fact the browser doing the mapping.

**Comment by offalynne** [comment]
GM doesn't do any remapping on HTML5. Due to the moving-target nature of per-browser gamepad implementation I think it's fine to continue to treat web as we do console and short-circuit SDL-style remapping altogether.

If we want VID/PID for ID type (lukewarm on this tbh), can leftpad the string.

**Comment by JujuAdams** [comment]
Fixed!
