### ISSUE TITLE
Change reported binding name for face buttons to NESW

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#110]
At the moment, binding names are tied to Xbox button labels (ABXY). For the sake of clarity, these should be changed to south/east/west/north respectively.

**Comment by offalynne** [comment]
https://github.com/JujuAdams/Input/commit/10a523720ebe5d6f082e0b2b4e85bac9e0900f0d

pls pardon direct commit 🤦‍♀️

**Comment by JujuAdams** [comment]
lol oops

**Comment by JujuAdams** [comment]
Yep looks good! Thanks for doing that @offalynne
