### ISSUE TITLE
Sometimes, XInput gamepads are not detected in Firefox

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#111]
For some reason, Firefox doesn't discover XInput gamepads but *does* discover DInput gamepads. Chrome is fine.

**Comment by JujuAdams** [comment]
Firefox is v90.0.2 for anyone wondering.

**Comment by JujuAdams** [comment]
I don't think there's anything we can do here. Gonna keep this ticket open to re-check whenever the next version of Firefox comes out

**Comment by offalynne** [comment]
Working fine for me! Mapped correctly as well.

http://offalynne.nfshost.com/input/

![image](https://user-images.githubusercontent.com/16347732/127942311-fb561431-0b59-40ee-9446-f91cad9d38a3.png)

https://www.amazon.ca/Microsoft-Xbox-Wired-Controller-Windows/dp/B004QRKWLA

**Comment by JujuAdams** [comment]
Bizarre!

**Comment by offalynne** [comment]
Tested and confirmed good on Win10 as well
