### ISSUE TITLE
os_type does not work on HTML5

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#113]

**Comment by JujuAdams** [comment]
GM bug, cross-platform. `os_windows` returns string literal `0a0 = 0` (expected integer `0`), `os_macosx` returns string literal `1a0 = 0` (expected integer `1`)

I'd venture that the leading digit(s) before `a` are the constant. We *can* make a workaround but unless the need is pressing then we should leave this be until YYG fix it

**Comment by offalynne** [comment]
🙈

**Comment by JujuAdams** [comment]
I think I might be wrong about this! My debug string was formatted wrong. Shall retest later

**Comment by JujuAdams** [comment]
False alarm probably? Seems to work as expected for me
