### ISSUE TITLE
Mac Browser keyboard tweaks

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#114]
Pending #113, if on Mac + Browser
add capslock to ignored keys (sticks) and relabel left & right meta keys.

**Comment by JujuAdams** [comment]
Done'd https://github.com/JujuAdams/Input/commit/c14969f5d17d84456c31a12691d4aad2337e466a

**Comment by offalynne** [comment]
Gotta fix meta (me)

**Comment by offalynne** [comment]
#115
