### ISSUE TITLE
Linux axis range incorrect

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#117]
Joystick axes on Linux seem to rest at 0.5 instead of 0, full range being 0 to 1 instead of -1 to 1.

**Comment by offalynne** [comment]
Note that this issue is *not* presenting on web, so solutions should take care to except browsers.

**Comment by offalynne** [comment]
Fixed in #119

**Comment by JujuAdams** [comment]
Confirmed fixed, gj
