### ISSUE TITLE
Default to radial deadzone on joysticks

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#131]
Current deadzone is applied as a cross where a circle is preferrable. Axial deadzones snap hard to cardinals.

Apply deadzone to axis pairs in case of joysticks instead of handling single axis independently:

```
if x < deadzone x = 0
if y < deadzone y = 0
```
:-(

```
if magnitude(x, y) < deadzone x = 0, y = 0
```
:-)

and then normalize as in the current implementation.

If particularly fond of the current squarish joystick output (axial deadzone) perhap offer as toggle/alternative

**Comment by offalynne** [comment]
On further tinkering I think what I ultimately want is to specify several methods that suit different applications from the raw axis pair’s values and deadzone definition ala Steam Input’s joystick curves (see also https://web.archive.org/web/20141025190105/http://www.third-helix.com/2013/04/12/doing-thumbstick-dead-zones-right.html). The existing output seems acceptable for the common case (2D character movement). Closing for now.

**Comment by JujuAdams** [comment]
Have you seen the [2D checkers](https://github.com/JujuAdams/Input/wiki/Functions-(2D-Checkers))? Their deadzone operates radially and should be exactly the same as the link you provided.

**Comment by offalynne** [comment]
I did not, just briefly peeked at input_get and assumed they’d work the same, thanks for pointing it out!

Interested in playing with some alternative curves eg. https://minimuino.github.io/thumbstick-deadzones/demo/
http://theinstructionlimit.com/squaring-the-thumbsticks
but that’s Me territory, existing behaviour looks good for Input!
