### ISSUE TITLE
Check out Android

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#132]
Binding seems broken (haven't investigated thoroughly)

**Comment by offalynne** [comment]
Since we support browser now (lol) perhaps a peek there too. Seems like the keyboard-case stuff likely applies on browser as well.

**Comment by offalynne** [comment]
I can't test web unfortunately, @JujuAdams input binding look OK to you on native?

**Comment by JujuAdams** [comment]
Shall check...

**Comment by JujuAdams** [comment]
Gamepad input via Chrome worked well with everything doing what it should. I did notice an issue with the gamepad description showing the wrong thing but I strongly suspect that's upstream (and it's probably an edge case regardless). Keyboard input in Chrome is a mixed bag - arrow keys return gamepad buttons _only_, numpad enter doesn't work, we don't get F keys but we do get transport controls (177 = rewind, 179 = pause/play, 178 = fast forward). Alphabetics are upper case regardless of modification with shift

Keyboard input on native is acceptable I think. My Apple Magic Keyboard labels weren't matching what a native app was returning but I think that's two ecosystems not lining up rather than a deeper issue. As noted elsewhere, alphabetics are lower case unless modified with shift (at which point they return the upper case letter). I managed to stick a tilde key though I think that was GM fuckup rather than us

Gamepad input via Android native is... just barely acceptable I think. After a fix (https://github.com/JujuAdams/Input/commit/9793b6517012f8a175373a4445663e302d7051bd) rebinding works and we're able to operate mostly normally. The big issue for Android is that we aren't getting GUIDs back that fit the typical SDL2 pattern and our SDL database is a little thin on the ground for these alternate GUIDs, we're getting some alternate value (I think you explained what that value was to me a while ago but I've forgotten). As a result, we cannot retrieve controller type or reliably apply mappings to fix issues as we do on other platforms. I'll push my PS4 GUID + remappings to the SDL2 database (here and upstream) but we're out on a fragile limb here I feel

**Comment by offalynne** [comment]
Excellent notes ty, lots for me to run with!

**Comment by offalynne** [comment]
Added a few (89) of my own maps to fatten out the the mapping DB a bit.

Some of the problems you encountered around PS4 and Switch controllers are due to foetal drivers and associated keymaps in the kernel version you're on, which are make things look worse than they are... it's not GREAT but it's serviceable I think.

> I think you explained what that value was to me a while ago but I've forgotten

The Android legacy GUID strings are a weird CRC on device info including name that I've not been able to exactly figure out, but they do work. Newer stuff (Bluetooth etc) use the more familiar Linux format.

I've got a (sloppy) APK for generating maps, feel free to hmu if you want that for mapping anything easier on your end.

**Comment by JujuAdams** [comment]
Yeah I'm fine with running with the current gamepad implementation on Android but I suspect we'll be dealing with edge case bugs for a while. I'm jsut irritated that we're being forced down a legacy path when GM clearly has access to the newer stuff >:(

Do you think any further keyboard/gamepad work is necessary on Android at this point? Should we expand the block list for keys?

**Comment by offalynne** [comment]
perhaps if `)` and `tilde` are reproducibly sticking for you, otherwise good for now i think

**Comment by JujuAdams** [comment]
k, shall do some focused testing tonight

**Comment by JujuAdams** [comment]
Found the issue: releasing shift before releasing the other key (e.g. 0 for `)`) causes the modified key to stick. This is repeatable with at least all number row symbols and all alphabetics. Not 100% sure how to handle this, should we clear _everything_ when shift is released?

**Comment by JujuAdams** [comment]
Switch Joycons definitely don't give us raw SL/SR buttons, with or without GM's native mapping

**Comment by offalynne** [comment]
> should we clear everything when shift is released?

probably :-x hopefully io_clear will do the trick. thanks for figuring this one out, i’ll dig into it.

1. has the blacklist fixed the kb-gamepad problem? got any data for for me?

2. can you make detailed notes of the guid + description of joycons and procon as well as the output each axis and button produces after using gamepad_mapping_remove? (note: it’s gonna be really messy). 

3. Can you share the version of Android OS you’re on?

Thanks !!

**Comment by offalynne** [comment]
Notes for gamepad mapping:

- Confirm mapping correctly applied from YYG-db
- Confirm mapping correct applied when auto-assigned (not in db, guess-map assigned based on ? keymaps maybe? by runtime)
- Confirm custom remapping correctly applied (when our DB overrides a YYG-db map)
- ~~Confirm purely custom remapping applied (no YYG-map, using our map)~~

**Comment by JujuAdams** [comment]
> hopefully io_clear will do the trick

Can't even get that far: we can't detect `vk_shift` at all.

&nbsp;

1. Yes, blacklist is filtering out the keyboard based on "keyboard" being in the device description
2. See below...
3. Android 11, kernel 4.14.113-21663430

&nbsp;

None of the devices I have are already in the SDL2 db, but I can confirm that building my own remappings works and that GM's native remapping seems fine for PS4 and XB1 by default with these exceptions:

- PS4 gp_select is on the Guide button
- XB1 gp_select is on the Guide button... which also acts as a shortcut to go back to the home screen. The actual two-boxes select button does nothing under GM's native mapping

If you thought that I couldn't connect my XB1 pad to Android, you were correct. The wind changed direction today so Bluetooth decided to let the devices pair.

&nbsp;

Mappings are as follows, after running `gamepad_remove_mapping()` across all devices:
- Switch Left Joycon `31613237643563656561633964393335`
  - Thumbstick X: `a0` (oriented for vertical hold)
  - Thumbstick Y: `a1` (oriented for vertical hold)
  - Thumbstick click: `b7` + `b16`
  - L: `b9`
  - ZL: `b17`
  - Minus: `b15`
  - Screenshot: `b16` + `b20`
  - No dpad
  - No SL/SR
- Switch Right Joycon `39373064396565646338333134303131`
  - Thumbstick X: `a0` (oriented for vertical hold)
  - Thumbstick Y: `a1` (oriented for vertical hold)
  - Thumbstick click: `b8` + `b16`
  - R: `b10`
  - ZR: `b18`
  - Plus: `b6` + `b16`
  - A: `b1` (actual label A, face button East)
  - B: `b0` (actual label B, face button South)
  - X: `b3` (actual label X, face button West)
  - Y: `b2` (actual label Y, face button North)
  - Home: `b5` (doesn't trigger OS-level home)
  - No SL/SR
- `34323437396534643531326161633738,Nintendo Switch Pro Controller,a:b0,b:b1,back:b15,misc1:b5,leftshoulder:b9,leftstick:b7,lefttrigger:b17,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:b18,rightx:a2,righty:a3,start:b6,x:b2,y:b3,platform:Android,`
- PS4 you have already!
- `36616131643361333337396261666433,Xbox Wireless Controller,a:b0,b:b1,back:b15,leftshoulder:b9,leftstick:b7,lefttrigger:a4,leftx:a0,lefty:a1,rightshoulder:b10,rightstick:b8,righttrigger:a5,rightx:a2,righty:a3,start:b6,x:b2,y:b3,platform:Android,`

**Comment by offalynne** [comment]
tysm !

> Can't even get that far: we can't detect vk_shift at all.

🔥🐶☕🔥

will get to tinkering with the rest of the provided data

**Comment by offalynne** [comment]
JoyCons blacklisted: https://gist.github.com/offalynne/07f78774e3d9ff00fc79200951ac1883/revisions#diff-d21944d284a477942c05fefd219e9ba7ae7be71830a49fc4939839ad07fd41da, issue for later #142

Maps upstreamed: https://github.com/gabomdq/SDL_GameControllerDB/commit/25bb8dc17a5bd3cda993549e44596abcfa857503

> I can confirm that building my own remappings works and that GM's native remapping seems fine for PS4 and XB1 by default with these exceptions [...]

manual suggests this was done deliberately, so should be working right 🤦‍♀️

**Comment by offalynne** [comment]
confirmed gamepad mapping scenarios are working as intended using 8BitDo SN30 Pro+ and Xbox One Wireless controller except
> Confirm mapping correctly applied when auto-assigned (not in db, guess-map assigned based on ? keymaps maybe? by runtime)

which is a cross-platform issue #144 

otherwise Android all good !
