### ISSUE TITLE
Keyboard input on iOS native is tanked

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#138]
Extremely broken behaviour including, but probably not limited to:
1. `keyboard_check()` is universally non-functional and does not return the state of any key
2. Running `keyboard_check()` _at all_ will sometimes cause the game to hard crash (without error message)
3. Using certain keys on the keyboard will increment/decrement gamepad button/axis values seemingly without rhyme or reason
4. Despite modifying gamepad values, GameMaker does not report any gamepad connection/disconnection activity nor does `gamepad_get_description()` return anything other than a blank string

_Not_ checking for keyboard input seems to prevent points 2+3 from occurring

**Comment by offalynne** [comment]
Sounds good (bad), thank you for confirming. Long anticipated this was the state of native.

**Comment by offalynne** [comment]
#139

**Comment by offalynne** [comment]
If you can confirm we're keyboard-pain-free on native now before pressing release on 3.4 I'd appreciate (patch is theory-only atm).
@JujuAdams

**Comment by offalynne** [comment]
Want to add for posterity that `gamepad_get_description()` works great and all supported devices match our existing type-by-description identification method. Index for normal gamepads starts at 1
