### ISSUE TITLE
New documentation

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#141]
See `/docs/` folder in master branch. Not a priority atm but needs to get done for the next major release.

**Comment by offalynne** [comment]
Let's de-nbsp-ify.. if you want big margins before sections that's a job for CSS ;-]

**Comment by offalynne** [comment]
Do you want PRs on `new-docs` or `master`

**Comment by JujuAdams** [comment]
Neither, please send PRs via carrier pigeons. The pigeons must be _dusky black with eyes of glamour emerald_. 

(Wanna do my first pass first then it's open for PRs)
