### ISSUE TITLE
Switch joycons misbehave on Android

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#142]
- Thumbsticks are orientated for vertical hold
- Left face buttons (dpad) are non-functional
- SL/SR non-functional
- L+R pairing to join two joycons is unsupported when tested (though should work apparently?)

**Comment by offalynne** [comment]
Android kernel is using a version of the Linux drivers that aren't quite production ready (dkms-hid-nintendo). *Eventually* (as in, with an Android update), all of the auto-pairing etc. should be taken care of. For now we're blacklisting:

https://gist.github.com/offalynne/07f78774e3d9ff00fc79200951ac1883#file-sdl2-guid-and-android-device-description-gamepad-blocklist-L7-L8

If come v4 this is still a problem (hint: it will be) we can add internal pairing for JoyCon couples if that's desirable.
