### ISSUE TITLE
Last verb activated functions

### ISSUE THREAD

**Issue by FaultyFunctions** [offalynne/Input#17]
It would be great to have a function to let you know what the last verb was that was activated. Maybe these could be multiple functions for stuff like last pressed and last released.

I was thinking it might also be beneficial to have these in stored in a stack as well? That way if you have two keys held and you let go, it'll give you the last last key held or pressed. This might be better as a separate function or implemented on the user's side though.

**Comment by JujuAdams** [comment]
Added [`input_check_press_most_recent()`](https://github.com/JujuAdams/input/wiki/Functions-(Checkers)#input_check_press_most_recentarray-playerindex) for 3.0.0pre002
