### ISSUE TITLE
Check multiple verbs in one function.

### ISSUE THREAD

**Issue by FaultyFunctions** [offalynne/Input#18]
This would be useful to save on typing redundancy and who doesn't love that?

Would it be possible for this to use the same function? I think it's doable to detect an array in GMS?

Could be used like: `if input_check([Verb.LEFT, Verb.RIGHT, Verb.UP, Verb.DOWN])`

Otherwise they can be separate functions but I'll leave that for what you think is best.

**Comment by offalynne** [comment]
yeah “any”, “all”, “one” and “none” are definitely nice to have as utilities.. either as enums for an optional second parameter or their own functions extending the existing one, depending on your style/inclination.

i agree w @FaultyFunctions that the default should be “any”

**Comment by JujuAdams** [comment]
Implemented for 3.0.0pre002. Documentation updated too: https://github.com/JujuAdams/input/wiki/Functions-(Checkers)

These functions only support **any** behaviour. People have asked about button combos and I think to implement additional logic for multiple verbs it should go through a hypothetical button combo system.
