### ISSUE TITLE
Accomodate mixed (keyboard+gamepad) input

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#19]
increasingly PC users are presented options for combining gamepad and mouse/keyboard input, termed "mixed" or "simultaneous" input. limiting "player" slots to either/or means either thrashing between modes when hotswapping is enabled, or being locked out of one or the other input source altogether.

https://www.pcgamingwiki.com/wiki/List_of_games_that_support_simultaneous_input

common devices that leverage mixed input include gamepads ([Steam Controller](https://www.gamasutra.com/blogs/ZachBurke/20151030/257920/The_5_Golden_Rules_of_Input.php#comment276602) and thus by extension any gamepad leveraging Steam Input,  and numerous Android gamepads that map selective buttons to keyboard), gameboards (Logitech G13, Wooting devices, CoolerMaster's [Aimpad enabled](https://aimpad.com/compatibility/) MK850 and ControlPad, Belkin's N50 line, Saitek PZ31A, Razer's Orbweaver and Tartarus lines), gamemice (ROG Chakram, Swiftpoint Z, Lexip Pu94), and burgeoning hybrid ergo devices like the [Azeron](https://www.azeron.eu/) and [3dRudder](https://www.3drudder.com/pc-gaming/)

generally the consensus is "indicate device type as gamepad, but do not lock-out mouse or keyboard input". i know this is a pain especially for assigning devices per player, but if mouse/keyboard pairing is acceptable perhaps all three in tandem isn't [entirely unreasonable](https://i.imgur.com/3nWHgwD.png) ;-)

**Comment by JujuAdams** [comment]
A mixed input source can be supported, sure, and when player input is set up for this then hotswapping will be disabled. This will require the developer to explicitly set a player's source to `INPUT_SOURCE.MIXED`, e.g. a menu option, and then provide controller assignment via Input's assignment feature.

**Comment by offalynne** [comment]
As discussed this is a single-player-only feature, and in the larger scheme of decoupling players from devices, a 'player' need only **claim one source**, **share one source** _(eg. two players on keyboard or [sharing one pad](https://gamertweak.com/wp-content/uploads/2021/06/overcooked-2-controls-ps.jpg))_, or **claim _all_ sources** _(mixed input)_. 

Want to add that while currently titled 'keyboard + gamepad' the most common use case is actually _mouse + gamepad_, where either the mouse is being simulated thru gamepad input (eg. Steam Input) or an analogue joystick is being simulated thru analogue key input (wide variety of ergo devices).

**Comment by JujuAdams** [comment]
Implemented
