### ISSUE TITLE
Reintroduce refined device-agnostic player cursor

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#193]
With the goal of supporting the PS4/PS5 touchpad-per-gamepad/player and supporting cursor-driven local multiplayer (eg. dual stick aim) would be nice to get this back in I think.

**Comment by JujuAdams** [comment]
Agreed. Was dealing with this yesterday and the dev in question had gotten really confused about best practice. We should spec this out.

**Comment by JujuAdams** [comment]
(Removing console tag because this affects every platform and listing every platform seems silly to me)

**Comment by JujuAdams** [comment]
(Or maybe it's not silly? It's not silly is it.)

**Comment by JujuAdams** [comment]
(lol actually that's pretty silly)

**Comment by JujuAdams** [comment]
Review time! https://www.jujuadams.com/Input/#/5.0/Functions-(Cursor)
Also mouse capture is here: https://www.jujuadams.com/Input/#/5.0/Functions-(Mouse)?id=input_mouse_capture_setstate-sensitivity
Up/down/left/right verbs defined here: https://www.jujuadams.com/Input/#/5.0/Configuration?id=mouse-touch-and-cursor

Does this cover everything?
