### ISSUE TITLE
Bug(s) in Opera GX runtime prevents accurate reading of gamepad type

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#204]
GM's `gamepad_get_description()` returns a hex-encoded string that vaguely describes what gamepad is connected. Unfortunately, this string is truncated and doesn't match known gamepad descriptions so this indicates OGX is using its own gamepad stack.

Additionally, `gamepad_get_guid()` returns a blank string.

At the moment we're guessing what type of gamepad is plugged in but it's very approximate.

**Comment by offalynne** [comment]
Description is always "Standard Gamepad", GUID is the hex string (what would usually be HTML5 description, truncated to 16 characters). Filed and confirmed w/ YYG QA.

**Comment by offalynne** [comment]
5 months and no fix from YYG ¯\_(ツ)_/¯ #270

**Comment by modalmodule** [comment]
could this be why the dpad on my ds4 doesn't work when it works fine on windows target? Or is there something else I can do to make it more cross-compatible? (using the ol' right-left technique atm)

**Comment by offalynne** [comment]
@modalmodule different bug, the fix is in this same patch for next release https://github.com/JujuAdams/Input/pull/270

you can download here https://github.com/offalynne/Input/archive/refs/heads/operagx_mapping_and_type.zip

**Comment by modalmodule** [comment]
> @modalmodule different bug, the fix is in this same patch for next release #270
> 
> you can download here https://github.com/offalynne/Input/archive/refs/heads/operagx_mapping_and_type.zip

@offalynne WOOHOO! I just copy pasted the changed code into my project and it works!! Thanks a bunch!

**Comment by offalynne** [comment]
Can probably close this since YYG don’t appear to interested in fixing this and we have it handled.

**Comment by offalynne** [comment]
Since YYG don’t seem intent on fixing I think we can call this done per https://github.com/JujuAdams/Input/pull/270/files#diff-35b769109b61ac952137b5af2b08d163d81368b900f25cdd06f55f2b02c60921
