### ISSUE TITLE
Support button-on-axes for gamepad maps

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#209]
Added 2 maps upstream that require this:
https://github.com/gabomdq/SDL_GameControllerDB/blob/b8f250ceed0982bc32c2dbd38b52342ece320aaa/gamecontrollerdb.txt#L698-L699

And it's permissible per the mapping spec:
https://wiki.libsdl.org/SDL_GameControllerAddMapping

> Buttons can be used as a controller axes and vice versa.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/3fd5fce9f0cf4bcd01afd8f346f7f3f91946291f
