### ISSUE TITLE
More functions to return cursor data

### ISSUE THREAD

**Issue by DragoniteSpam** [offalynne/Input#21]
I often like to include a few variables to keep track of cursor movement between frames - drawing a cursor on the UI but having it disappear if the mouse hasn't moved in the last three seconds, for example.

        mouse_x_previous = mouse_x_window;
        mouse_y_previous = mouse_y_window;
        
        mouse_x_window = window_mouse_get_x();
        mouse_y_window = window_mouse_get_y();
        
        mouse_x_delta = mouse_x_window - mouse_x_previous;
        mouse_y_delta = mouse_y_window - mouse_y_previous;
        
        if (mouse_x_previous != mouse_x_window || mouse_y_previous != mouse_y_window) {
            mouse_last_moved = current_time;
        }

It doesn't look like Input contains anything to do that yet. Would be useful on occasion!

**Comment by JujuAdams** [comment]
Thanks for your suggestion. I'll have a think about what can be implemented

**Comment by JujuAdams** [comment]
Implemented for 3.1.1:

`input_cursor_prev_x([playerIndex])`
`input_cursor_prev_y([playedIndex])`
`input_cursor_moved([playerIndex], [bufferDuration])`

The last function will handle "moved within a time window" for you if given a buffer duration (whether this is realtime or frame-counting depends on macro `INPUT_TIMER_MILLISECONDS`)

**Comment by DragoniteSpam** [comment]
ooh, this is going to be handy. thank!
