### ISSUE TITLE
Configurable gamepad initialization delay

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#212]
Per cosmonaut on discord, Steam opens a virtual device (probably per non-XInput pad) that doesn't disconnect until some duration later (probably Steam Overlay startup).

A default-off config like `INPUT_GAMEPAD_INIT_DELAY` would help prevent false positives on boot and save on potential issues related to premature connection and disconnection events.

**Comment by JujuAdams** [comment]
Looks like 1 frame isn't enough and cosmonaut recommends somewhere in the region of 10 frames. Seems like a reasonable default delay.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/96380ad94b4e19349d2efeb373c4adcb1fc79a68
