### ISSUE TITLE
input_verb_set() not triggering input_check_... functions

### ISSUE THREAD

**Issue by uglycoal** [offalynne/Input#223]
Using `input_verb_set()` in Begin Step event before `input_tick()` changes verb value, but seemingly does not trigger any of the checks I have in my game.

Doesn't seem to work if set once or being done continuously.

Even just force setting a specific verb before `input_tick()` will show it as 1, blocking the ability to use actual button, but not triggering `_check_` OR `_check_pressed` Input functions.

**Comment by JujuAdams** [comment]
Shall take a look soon!

**Comment by offalynne** [comment]
Working as intended I think (tick first, set after)

**Comment by uglycoal** [comment]
Yea, offalynne. Moved verb setting logic to Begin Step of a virtual button (it's created after input manager, so should run the code after that too). So verb is set before any checks and it seems to be working like this now.
Can't remember why I did it the old way at all, so, guess it's not a bug!

**Comment by offalynne** [comment]
@JujuAdams might want to clarify how it's *supposed* to work just to be sure https://discord.com/channels/724320164371497020/725060331759730738/920434325634289695

**Comment by offalynne** [comment]
As in the test example, only setting *after* tick works, and only for `check`, not `check_pressed` or `check_released`

**Comment by offalynne** [comment]
#271

**Comment by JujuAdams** [comment]
Reopening until PR has been reviewed

**Comment by JujuAdams** [comment]
PR approved!
