### ISSUE TITLE
Remove blocklist platform category wildcard `all`

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#226]
As of #225 all blocklist rules are platform specific. Per-platform driver discrepancies mean blocks should always be platform dependent.

There was one exception briefly (Switch Pro) but Linux and Android now ship kernel drivers for it. Seems good practice generally to specify platform.

**Comment by JujuAdams** [comment]
Merged #225, all done

**Comment by offalynne** [comment]
Redundant handling stuff can go: https://github.com/offalynne/Input/blob/dev/scripts/__input_gamepad_set_blacklist/__input_gamepad_set_blacklist.gml#L14-L39

Can author PR later

**Comment by JujuAdams** [comment]
Accepted #233, thank you kindly
