### ISSUE TITLE
Touchscreen virtual buttons

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#230]

**Comment by offalynne** [comment]
```
var _id = input_virtual_button_add(x, y, verb, [depth], [collision func], [draw func]);
input_virtual_button_disable(_id);
input_virtual_button_enable(_id);
input_virtual_button_remove(_id);
var _list = ..._get_list()
```

provided presets for collision/drawing: circle, rect, trilist?

updates handled by tick

also -- virtual axes via radial touch input? fixed position or relative w/in rect

**Comment by offalynne** [comment]
strikes me that the native solution might work just fine tbh. should at least survey them to compare.

**Comment by JujuAdams** [comment]
Native solution won't allow us some of the more advanced features but, yeah you're right, it probably works already.

**Comment by offalynne** [comment]
besides buttons i suppose..

virtual joystick (static or dynamic)
virtual dpad (overlap or

**Comment by offalynne** [comment]
The more I think about this the more I think it's out of scope and means adding too much opinionated/prescriptive interface related overhead to the library. Preferable to just point toward `input_verb_set` and leave implementation up to the library user.

**Comment by JujuAdams** [comment]
Fuck it, let's give it a go. Good opportunity for me to learn more about touch interfaces regardless.

**Comment by JujuAdams** [comment]
Implemented! Now needs testing.
