### ISSUE TITLE
Accessibility feature to "rate limit" button presses

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#232]

**Comment by offalynne** [comment]
https://gameaccessibilityguidelines.com/include-a-cool-down-period-post-acceptance-delay-of-0-5-seconds-between-inputs/

**Comment by JujuAdams** [comment]
boy oh boy I have no idea how to do this

**Comment by offalynne** [comment]
consume until timeout ?

**Comment by offalynne** [comment]
anti-buffer, n’est pas ?

**Comment by JujuAdams** [comment]
https://gameaccessibilityguidelines.com/include-a-cool-down-period-post-acceptance-delay-of-0-5-seconds-between-inputs/
