### ISSUE TITLE
GM disregards internal dpad key maps on Android

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#237]
On Android, if GUID is normative (currently determinable in Input by whether VID & PID loaded),

`dpdown:b12,dpleft:b13,dpright:b14,dpup:b11` 

mappings need to be replaced with

`dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1`

This is currently breaking Xbox, PS, and likely other dpad mappings on Android.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/6fbf45e98525d629dab20d492466bacdf5b50881 ???

**Comment by offalynne** [comment]
Should have clarified, this is *only* an issue for mappings that are coming from the SDL db. I thought about fixing it in the Python data consumer stage but since our goal is to support drop-in of the native DB it should be handled internally by Input.

**Comment by JujuAdams** [comment]
Oooooh ok, I will deal with this another way then

**Comment by offalynne** [comment]
#238
