### ISSUE TITLE
`player_gamepad_get_dpad_style` can probably be binned

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#249]
same class of checker as button color and button label -- direct checker alone should suffice

**Comment by JujuAdams** [comment]
Yes, probably a bit fiddly. I feel similarly with the description getter since I doubt that sees much use outside of debugging but idk... the symmetry with GM native feels nice

**Comment by offalynne** [comment]
yeah i think in the interest of encouraging use of 'type' above all for gamepad classification, player gamepad description can go as well

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/d260d04dedf0c2b62ecb0e527bbf4aabc637820b
