### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by ScottGrogin** [offalynne/Input#292]
V4.2 of the documentation quick start guide mentions needing to set up a begin step event twice.
https://www.jujuadams.com/Input/#/latest/Quick-Start-Guide

The following is from step 1,

"Now since we’re on a roll, why don’t you make an input manager object. I’m gonna call mine `obj_input_manager`, but you might have a better or funnier name or whatever. Add yourself a Create event, a Begin Step event, and a Begin Step Event."

**Comment by offalynne** [comment]
Fixed, thanks
