### ISSUE TITLE
Optional argument `negatingVerb` for continuous checkers

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#294]
per @Lojemiru on Discord, allow a specified "cancelling" verb to negate continuous checkers for easier action state resolution:
- `input_check`
- `input_check_repeat`
- `input_check_double`
- `input_check_long`

**Comment by offalynne** [comment]
fwiw *without* this feature, library user need only
`someAction = input_check_..(verb) && !input_check(negatingVerb);`

**Comment by JujuAdams** [comment]
#337 #338
