### ISSUE TITLE
Saving and Loading Binds to an External File

### ISSUE THREAD

**Issue by GhostlyFeline** [offalynne/Input#31]
It would be useful to have a way to put the player bindings into an external file so that players could have their control preferences set correctly the next time they open the game.

**Comment by JujuAdams** [comment]
Implemented `input_bindings_write()` and `input_bindings_read()` (and `input_bindings_reset()`) for v3.1.0pre. These export/import strings so it's down to you to store them how you want. The repo contains a save/load test case that uses a buffer; this is broadly what I'd recommend
