### ISSUE TITLE
universal toggle for accepting "real device" Input

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#314]
Now that `verb_set` is mature and Steam Input as well as virtual/touch controls for mobile are on the radar, an easy way to early-out builtin checkers altogether so `verb_set` can take over in the appropriate contexts would be helpful

**Comment by offalynne** [comment]
Though perhaps this is precisely what `GHOST` is for ?

**Comment by offalynne** [comment]
Perhaps this is `GHOST` use case ?

**Comment by JujuAdams** [comment]
Either make the player a ghost or create an empty profile
