### ISSUE TITLE
[4.2] HTML5 crash on LTS

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#324]
from Discord

> input_tick() .. above L393 .. In the gamepad status struct .. gamepad_get_device_count() is returning 0, which is in turn causing Input to crash on HTML5

> I got a workaround that works. But needs opinion/further testing.
```
    var _count = gamepad_get_device_count()-1;
    var _g = 0;
    repeat(INPUT_MAX_PLAYERS)
    {
        if (_g > _count) break;
```

Feel free to author a PR or let us know where the patch goes @tabularelf

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/22aecb3ae43b6cf3d74160e5c540ecf501eff7f2
