### ISSUE TITLE
Be able to distinguish mouse & keyboard use

### ISSUE THREAD

**Issue by morphonet** [offalynne/Input#33]
I'd like to be able to activate a mode that gives me more detailed states with "input_player_source_get()"

For now, enum INPUT_SOURCE has NONE, KEYBOARD_AND_MOUSE, GAMEPAD

After a call to a function like input_distinct_mouse_keyboard(true), i'd like to be able to get in the INPUT_SOURCE enum some more details, with NONE, KEYBOARD, MOUSE, GAMEPAD

**Comment by offalynne** [comment]
MKB source should be split into separate sources and the grouped source reauthored to call both. 

Example of the uncommon-but-not-unheard-of exclusive mouse source: [Jamestown](https://i.imgur.com/VAQUT5d.png)

**Comment by JujuAdams** [comment]
Implemented
