### ISSUE TITLE
Add a tracker for what verbs input_rebind_tick()

### ISSUE THREAD

**Issue by Andre-404** [offalynne/Input#35]
It would be great if upon success input_rebind_tick, if a swap between keybindings has happend, the function returns with what verb has the swap occured.

**Comment by JujuAdams** [comment]
Thanks for making this request. I'll let you know how I get on as I'm making it

**Comment by JujuAdams** [comment]
Will be implemented v3.2.0

**Comment by JujuAdams** [comment]
Redundant as of v3.2.0 due to changes in binding/rebinding system
