### ISSUE TITLE
Check for "quick tap" input

### ISSUE THREAD

**Issue by Craftis** [offalynne/Input#377]
Not sure if this already exists but it would be pretty neat to have a feature where you can check if you've quickly tapped the control stick on a gamepad to replicate smash bros' smash inputs.

**Comment by offalynne** [comment]
`tappedRight = input_check_released(“right”, playerindex) && !input_check_long_released(“right”, playerIndex, tapDurationLimit);`

**Comment by JujuAdams** [comment]
Fantastic suggestion! We'll slate that for 5.1 as a native feature; until then you can lean into the input buffering feature to build the feature yourself e.g. `input_check_release("verb", <playerIndex>) && input_check_pressed("verb", <playerIndex>, <quickTapDuration>)`

**Comment by offalynne** [comment]
on reflection this is actually a different feature than the proposed method (#387): it’s an acceleration test: zero-to-threshold, not pressed-to-released. you can for example, complete the input with the thumbstick still engaged.

perhaps `input_check_tapped(verb, tapDuration, <tapThreshold>, <playerIndex>)`

**Comment by offalynne** [comment]
@Craftis1024 can you join us to discuss the feature on Discord ? https://discord.gg/8krYCqr

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/6e4bfe9e80dd2484864f1920b366ead2ec0b0aba
