### ISSUE TITLE
Generic joystick handling

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#390]
Presently, gamepad device handling assumes all joystick devices are gamepads. As long as library users assume this as well, no issues arise.

However, if a player plugs in a flight stick, wheel device, guitar controller, or other non-gamepad-like device, their device will be:
- Incorrectly assumed to be a gamepad
- Given a generic fallback mapping (as the mapping DB deliberately omits such devices)
- Likely unable to bind extended features
- Likely to exhibit incorrect information (eg. prompts)

A potential (nontrivial) solution is to identify such devices by whitelist (SDL does this) and offer full unmapped “raw” bindings based on all available axes, buttons, hats.

Since GM does not tend to be the tool of choice for alternative device driven games (driving sims, flight sims, music performance sims) this is probably a nonissue — but should library user interest arise, it is possible to accomplish.

**Comment by JujuAdams** [comment]
What would the developer-facing API look like?

**Comment by offalynne** [comment]
non-gamepad joysticks (whitelisted or not found by gamepad type ID) are not assigned a mapping and any button/axis/hat value within bounds can be set by binding, directly checked (by existing gamepad functions), returned as a valid binding. would use existing gamepad checkers.

not entirely sure what work is entailed yet, at minimum probably several new gamepad binding types ?

**Comment by JujuAdams** [comment]
`input_binding_raw_gamepad_button()` etc?

5.3 perhaps for this feature?

**Comment by offalynne** [comment]
closed by #742, #750, and #747,
