### ISSUE TITLE
Nonzero gamepad axis blocks hotswap

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#399]
Nonblacklisted gamepad axes resting at nonzero blocks source hotswap

**Comment by offalynne** [comment]
Primary issue is PS4 controller stuck in a bad state on Windows — triggers stick at 0.5

**Comment by offalynne** [comment]
#441

**Comment by offalynne** [comment]
Fixed for PlayStation controllers. Long term solution is tracking analogue value change over time, or perhaps comparing to analogue value upon connection

**Comment by JujuAdams** [comment]
See https://github.com/JujuAdams/Input/commit/0fac374cf3bbbdf06f4094dbb117de0305b4b184 + https://github.com/JujuAdams/Input/commit/09d394b4db790a0db9f0aa61cc42a3a1e9e2be2a. Do we still need the [PlayStation-on-Windows check](https://github.com/JujuAdams/Input/blob/dev/scripts/__input_hotswap_tick/__input_hotswap_tick.gml#L54-L57)?

**Comment by offalynne** [comment]
Will test ! Hopefully not 🥳

**Comment by offalynne** [comment]
All clear, #476
