### ISSUE TITLE
Connecting multiple gamepads of different types produces incorrect device name (description) on iOS

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#405]
~~Issue does not seem to exhibit in GM runner normally, eg. printing connected gamepad descriptions in a blank project~~

Upstream bug after all. This is a hotplugging issue: restarting the app after pairing controllers behaves as expected

**Comment by offalynne** [comment]
Bug filed with YYG

**Comment by offalynne** [comment]
Fixed upstream

**Comment by JujuAdams** [comment]
Do you know which GM version this was fixed in?

**Comment by offalynne** [comment]
[Beta Runtime 210](https://gms.yoyogames.com/release-notes-runtime-NuBeta.html)
> *In-Game: [iOS] gamepad_get_description() values do not update correctly when multiple devices are paired mid-game*
