### ISSUE TITLE
Unable to set keyboard icons in config due to (new?) struct key name limitations

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#410]
> _the numrow numbers and other unique special characters like hyphen, period, comma, etc._

![5EA8EF5D-6F42-41F7-8101-098A480CE19E](https://user-images.githubusercontent.com/16347732/180594801-ac01467d-feba-443a-8dcf-1dc71406c42d.png)

**Comment by offalynne** [comment]
#411

**Comment by JujuAdams** [comment]
Addressed in 5.1
