### ISSUE TITLE
Warning about version mismatch when importing to GMS 2.3+

### ISSUE THREAD

**Issue by pdseventyeight** [offalynne/Input#429]
Whenever I drag Input5.yymps into a project in GMS 2.3+, I get the following warning:

Project version is newer than supported version in CoreResources, marking as read-only as we can't safely support this: 1.6 > 1.5

I have no idea where this is coming from or what it means, but it's probably unnerving for people who want to use Input5 without studying its deep inner workings.

**Comment by JujuAdams** [comment]
We do not officially support versions before GameMaker Studio 2022.5.

**Comment by pdseventyeight** [comment]
I _am_ using GMS 2022.5+

I downloaded the yymps file from the website, and after dragging it into a GMS2 project, I still got that warning.
![Input5_Warning](https://user-images.githubusercontent.com/110518619/182958468-ee48e452-887d-44d7-a75d-2ecaf56b04ac.png)

**Comment by pdseventyeight** [comment]
> We do not officially support versions before GameMaker Studio 2022.5.

https://github.com/JujuAdams/Input/issues/429#issuecomment-1205801580
