### ISSUE TITLE
Newbie guide somewhat lacking

### ISSUE THREAD

**Issue by pdseventyeight** [offalynne/Input#430]
I'd like to propose a rework of the documentation for this wonderful package.

There is a really short "Newbie guide" section, and after that, there seems to only be the technical documentation that lists individual functions etc.

The Newbie guide says this:
Let’s define some verbs then! To define default bindings for your verbs you’ll need to edit the INPUT_DEFAULT_PROFILES macro found in __input_config_profiles_and_default_bindings().

Unfortunately, it doesn't instruct the "Newbie" that *__input_config_profiles_and_default_bindings()* is a **script file** hidden inside "Input" --> "Configuration - Please edit these scripts!".

The next bit is also quite head-scratching:

> When you import Input it’ll come with some default controls already set up. To explain this clearer, let’s delete everything that’s already in INPUT_DEFAULT_PROFILES and start fresh. You may also need to delete the contents of INPUT_VERB_GROUPS too.

This "Let's delete stuff and rewrite it" approach is weird.

I don't want to quote the entire page here, but sentences like:
> Here’s a Step event for you to put in a character object or whatever!
> Now, run the game and look at your hard work! Dang, aren’t those inputs tasty? Ooh, looky here, buttons!
or
> Oh you sweet summer child, did you think we were done?

do create some weird impressions (such as "Will some touch buttons appear on the screen? Or what *buttons* are they talking about here?")

And that's basically it!

In a "Newbie tutorial", I would expect - and that's what I'm proposing - a TUTORIAL approach:
1. Tell them what you're about to teach them.
2. Then tell them what to do.
3. Then let them see what it DOES.
4. Then explain WHY it DOES it: how does each thing they did connect with what it does.
5. Then build on top of that with the next step.

At the very least, the Newbie section should feature:
1. binding several different inputs to the same verb ("shoot").
2. Checking for the input and shooting.
3. checking for a DOUBLE CLICK/DOUBLE TAP to achieve a different action using the SAME input (Something like "Double Tapping the shoot input will instead lob a grenade").
4. Resolving the issue that when you double tap, it first shoots and THEN lobs a grenade -- how do I prevent the single shot when double tapping?

**Comment by JujuAdams** [comment]
Please author a PR with your recommendations.
