### ISSUE TITLE
input_profile_export returns "true" instead of a profile string

### ISSUE THREAD

**Issue by Journoid** [offalynne/Input#438]
When _output_string is set to true, the function only returns "true."
Tracing it down, the issue lies in line 214 of __input_class_player.gml. It's returning json_stringify(_output_string) instead of json_stringify(_output)
![input bug](https://user-images.githubusercontent.com/15371172/184012897-12ddf2d8-c636-4f41-9f96-cd4ea1f939f1.png)

**Comment by JujuAdams** [comment]
How embarassing.

**Comment by JujuAdams** [comment]
Solved for new release
