### ISSUE TITLE
PS4 controllers may fail to enumerate on Windows

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#440]
[alynne edit]
see https://github.com/libretro/retroarch-joypad-autoconfig/issues/852#issuecomment-1220880439

**Comment by offalynne** [comment]
Bad Windows driver is the culprit. In device manager, if a BT-paired PS4 controller shows up under "Sound, video and game controllers" with 'View > Show hidden devices' enabled, in Properties, `Driver > Uninstall Device > Uninstall`, restarting, then repairing fixes the issue.

**Comment by offalynne** [comment]
#441

**Comment by offalynne** [comment]
https://github.com/libretro/retroarch-joypad-autoconfig/issues/852#issuecomment-1220880439

**Comment by offalynne** [comment]
Should update quirks docs
