### ISSUE TITLE
input_source_share() crashes

### ISSUE THREAD

**Issue by SadColor** [offalynne/Input#448]
I think it's because __INPUT_VERIFY_PLAYER_INDEX is accidentally placed at the start of the function.

```gml
local variable _player_index(101304) not set before reading it.
 at gml_Script_input_source_share (line 11) -     __INPUT_VERIFY_PLAYER_INDEX
```

**Comment by JujuAdams** [comment]
You would indeed be correct! Thank you for reporting this. If you remove that line of code, does source sharing work as expected?

**Comment by SadColor** [comment]
Yes, it seems to work fine if the line is removed.

**Comment by JujuAdams** [comment]
Lovely, thanks.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/cf9c1dfbd7de4a5c1ec455da5af2243457492314
