### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#454]
- Quirks
    - [ ] Windows PlayStation/Switch controller BT woes
    - [ ] iOS gamepad type woes
    - [ ] Window focus
- Add 
    - [x] Haptics
        - [x] Pause vibration
    - [x] `_available_only` arg for `input_source_detect_input`
    - [x] `opposing` checks renamed
    - [x] `input_held_time_released`
    - [x] `input_mouse_in_bounds`
    - [x] `input_window_has_focus`
    - [x] `INPUT_ALLOW_OUT_OF_FOCUS`
    - [x] `input_binding_scan_*_params`
    - [x] quick tap functions
    - [x] `INPUT_QUICK_BUFFER`
    - [x] Info re. auto/manual ticking
    - [x] `input_cursor_translate()`
- Remove 
    - [x] `input_gamepad_get_dpad_style`

**Comment by JujuAdams** [comment]
Documented vibration functions
