### ISSUE TITLE
Motion data, trigger haptics, RGB

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#467]
Additional features similar to #390: things we _can_ add should library user interest arise. I think GM is not often used to make the kind of games that want to utilize these features, but access is available if we hear otherwise. From most to least relevant:
- Motion data
   - On console (Switch and PlayStation platforms)
   - Native motion devices (Linux modules, DsHidMini, etc.)
   - Many UDP servers on desktop platforms (BetterJoy, DS4Windows, evdevhook, etc.)
- Trigger haptics
   - On console (PS5)
   - UDP server on desktop platforms (DualSenseX)
- RGB
   - On console (PlayStation platforms)
   - UDP server on desktop platforms (OpenRGB)
   
These assume unextended GM; all of the above are additionally available via Steamworks interface.

**Comment by JujuAdams** [comment]
I am going to firmly kick this can down the road. I will hopefully be involved with some console porting next year and that would likely be the best time to tackle these tasks as I'll have hardware to hand.

**Comment by JujuAdams** [comment]
> I am going to firmly kick this can down the road.

To which Alynne said "November will do" https://github.com/JujuAdams/Input/pull/510 https://github.com/JujuAdams/Input/pull/514
