### ISSUE TITLE
Input doesn't recognize Gamepad Icons for Player 2, if Player 1 uses Keyboard and Mouse. 

### ISSUE THREAD

**Issue by qlak** [offalynne/Input#477]
1. **PROBLEM:**
- Icons associated with Xbox Controllers do not show up, when Player 1 uses Keyboard. Input takes the icons from "unknown" device. It also spams error logs all the time, because of this.
&nbsp;

2. **DETAILED INFO:**
- It was tested with Xbox360 and XboxOne Controllers.
- **CASE 1**: If Player 1 uses Controller and Player 2 uses Keyboard, the proper icons for both players and their devices will show up.
- **CASE 2**: If Player 1 uses Controller and Player 2 uses Controller, the proper icons for both players and their devices will show up.
- **CASE 3**: If Player 1 uses Keyboard and Player 2 uses Controller, then only Player 1 will see proper icons set up for keyboard, but Player 2 will see the icons from "Unknown" device. Also Input will print the warning log in the console stating: "_Warning! Could not find valid icon for "gamepad face east" using "unknown"_".
- It does not matter if we use sprites as icons or just text.
- Code used to test it was the same for all cases, only input was changed for each player, with use of _INPUT_SOURCE_MODE.JOIN_.
- The Controller used by Player 2 is recognized by Input, because: _input_gamepad_get_type(input_player_get_gamepad(1))_ function returns "Xbox One" and not "Unknown". Only the icons are affected.
&nbsp;

3. **REPRODUCTION:**
- This Bug occurs **ONLY when Player 1 uses Keyboard and Player 2 uses Gamepad** (_it was tested with Xbox360 and XboxOne controllers_).
- The easiest way to test it, is by adding sprites as icons, but it is also possible to use different texts as Icons.
- If we are using text instead of sprites, then it is important to change the default "A", "B"... icons from Xbox One controller in ___input_config_icons_ script to a something like "XBOX ONE - A", "XBOX ONE - B"... for testing purposes, because the Unknown device has "A" and "B" also set up and it would look the same. 
&nbsp;

4. **ATTACHMENTS:**
- Logs that show up, when CASE 3 (P1 Keyboard, P2 Controller) runs:
> Input: Warning! Could not find valid icon for "gamepad face east" using "unknown"
> Input: Warning! Could not find valid icon for "gamepad face south" using "unknown"

- Example taken from the running game, with all 3 cases:

![IconBugExample](https://user-images.githubusercontent.com/33029999/190243778-52956e7a-b9d9-4230-8fe1-75cc4a53ad90.png)

**Comment by JujuAdams** [comment]
What code are you using to show get the icon for the binding?

**Comment by qlak** [comment]
input_binding_get_icon(input_binding_get(inputVerb, playersDeviceIndex));

Works as you can see on the screen above.

**Comment by JujuAdams** [comment]
As we discussed on Discord, `input_binding_get_icon()` requires the player index as well. The official example in the repo also has the exact same bug so... yeah, I'll try to make this easier to use in the future

**Comment by qlak** [comment]
input_binding_get_icon also needed 2nd argument, so this is the solution:

input_binding_get_icon(input_binding_get(inputVerb, playersDeviceIndex), playersDeviceIndex);
