### ISSUE TITLE
Simpler icon getter

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#482]
Presently need to specify player and profile twice

**Comment by JujuAdams** [comment]
Rename current `input_binding_get_icon()` to `input_binding_get_icon_ext()`, and replace with `input_binding_get_icon(verb, [playerIndex], [alternate], [profileName])`

**Comment by JujuAdams** [comment]
Better idea: Add `input_verb_get_icon()`

https://github.com/JujuAdams/Input/commit/ecc835285f71101a58a7ea400b7d1dc1743ca176
