### ISSUE TITLE
Support for touch input on mobile devices

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#493]
IT IS TIME

I'll likely need to do some work in this direction in the next couple years anyway so it'd be good to learn more about touch interfaces in general.

**Comment by offalynne** [comment]
Peep [obj_test_touch](https://github.com/JujuAdams/Input/tree/master/objects/obj_test_touch), still holds as the suitable platform-normalising solution, I think.

Current solution solves “best touch” from many, for easy mouse parity.

Perhaps we want…
 - Multitouch checker ? Not sure what utility we can offer
 - Gesture recognition ? In the vein of native checkers, perhaps a good survey of their strengths/shortcomings/use cases may be informative
 - Virtual controls

**Comment by JujuAdams** [comment]
We've got a virtual buttons ticket in #230 so let's deal with that there.

Multitouch I agree we can't do a lot. Maybe we could divide up the screen into portions and tie a touch that starts in a particular e.g. quadrant to a particular player via the cursor system? Would need to allow the dev to define player "zones".

Gesture recognition I'd like to look into, at least two-finger scrolls, zooms, and rotations. Three-finger gestures... eh...

**Comment by JujuAdams** [comment]
Oh also one-finger flick

**Comment by JujuAdams** [comment]
Gonna ditch touch gestures as not especially helpful for games. Flicks/fast swipes can be implemented using virtual buttons if the developer wants.
