### ISSUE TITLE
Support for touch input on non-mobile devices?

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#494]
Not entirely sure where we're at with touch support in general, and especially not for non-mobile devices.

**Comment by offalynne** [comment]
Fun stuff: GM always and inextricably conflates physical mouse with first touch index.

**Comment by offalynne** [comment]
On Desktop, touch is just a mouse (fine, pretty much how the OS operates anyway). ~~No multitouch support.~~ (Edit: Windows support, per beta)

On mobile, reported real mouse position doesn’t update until a button press. Multitouch supported.

On browser, touch works as on PC or mobile.

On Switch, real mouse is conflated w first touch index. Position updates when you move even without click (unlike mobile platforms) making it the only touch platform you can reliably get a whiff of real mouse as opposed to touch. Multitouch supported.

Runner on PlayStation doesn’t support real mouse. Touch indices are 2 per controller. Touch coordinates are relative to an onscreen cursor. Press/release is handled for the physical touchpad button (first of each pair) so you can only guess at touch press/release by checking for coordinate change.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/pull/526
