### ISSUE TITLE
Add functionality to limit what keyboard keys are permitted to be returned by input_binding_scan_tick()

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#51]
It's possible to scan the generated binding post-hoc but this is annoying. A feature should exist to prevent certain keys from being interpreted as valid inputs.

Additionally, these blocked keyboard keys should not trigger a switch to keyboard usage.

**Comment by offalynne** [comment]
I recommend reserving Alt and Meta (Cmd/Win/etc) keys on Linux (GTK) and Windows. Problematic combos with Alt include Alt Space, Alt Tab and Alt Shift which cause key sticking among other things. Meta key obviously steals focus and is reserved for other OS-level shortcuts.

On Mac Alt is fine, but Meta (Cmd/Win/etc) isn't -- it buffers all key presses while held and dumps them all on the frame it's released.

Aside from these two nothing seems particularly egregious to me. Perhaps system stuff like NumLock & ScrollLock (some people do like binding CapsLock for stuff), IME keys (0x15 - 0x1A, 0xE5), browser keys (0xA6 - 0xAC), media keys (0xAD - 0xB7).

**Comment by offalynne** [comment]
Not worth blocking but perhaps worth a comment in source -- reserved platform combos:

> **Steam and GOG**
> Shift Tab: Overlay
> F12: Screenshot
> 
> **Origin**
> Shift F1: Overlay
> 
> **Epic**
> Shift F3: Overlay
> 
> **UWP**
> Meta Shift Enter: Toggle fullscreen
> Meta Shift Arrow: Switch display
> 
> **Discord**
> Shift ` (Backtick): Overlay
> 
> **Windows 10 Xbox Game Bar**
> Meta G: Overlay
> Meta Alt G: Record clip
> Meta Alt R: Recording toggle
> Meta Alt PrtScrn: Screenshot 
> Meta Alt M: Mic toggle
> Meta Alt B: Broadcast toggle
> Meta Alt W: Show camera
> 
> **NVIDIA Shadowplay**
> Alt Z: Overlay
> ` (Backtick): Push to talk
> Alt F1: Screenshot
> Alt F5: Broadcast overlay toggle
> Alt F6: Camera toggle
> Alt F7: Broadcast pause/resume
> Alt F8: Broadcast toggle
> Alt F9: Manual recording toggle
> Alt F10: Save clip
> Alt F12: FPS counter toggle
> 
> **GeForce Experience**
> Ctrl G: Overlay
> Ctrl 1: Screenshot
> Ctrl 9: Manual Recording Toggle
> Ctrl Shift 0: Instant Replay Toggle
> Ctrl 0: Instant Replay Save
> Ctrl M: Mic Toggle
> _All Shortcuts are Meta (Cmd) instead of Ctrl on Mac_
> 
> **Parsec**
> Ctrl Shift C: Chat
> Ctrl Shift M: Menu toggle
> Ctrl Shift W: Toggle windowed
> Ctrl Shift I: Immersive mode
> Ctrl Alt Z: Detach mouse
> Ctrl Alt End: Send Ctrl Alt Del
> Ctrl Alt ' (Single quote): Disconnect (Windows)
> Meta Q, Meta W: Disconnect (Mac)
> Ctrl Alt ~: Disconnect (Linux)
> Ctrl F1: Allow pending join request
> Ctrl F3: Kick everyone connected (panic button)
> Ctrl Shift C: Switch display
> Ctrl Shift S: Second screen
> Ctrl Shift P: Enhanced pen
> 

Most of these are directly intercepted so they won't accidentally bind, but conflicts should be considered when defining default keyboard binds for a game.

**Comment by DragoniteSpam** [comment]
> Aside from these two nothing seems particularly egregious to me. Perhaps system stuff like NumLock & ScrollLock (some people do like binding CapsLock for stuff), IME keys (0x15 - 0x1A, 0xE5), browser keys (0xA6 - 0xAC), media keys (0xAD - 0xB7).

I kinda feel like if a user chooses to bind an action to one of the Media keys and it makes things weird in their game when they have iTunes open, that's on them. ¯\\\_(ツ)\_/¯

Otherwise who knows, maybe someone's into doing challenge runs where they have to play the game using only the Play/Pause button and Volume knob.

**Comment by offalynne** [comment]
i strongly disagree that deliberately reserved shortcut keys should be exposed, and i don't want games mistaking volume adjustment for input binding, but perhaps a constant to opt out of the limitation is suitable :-)

**Comment by JujuAdams** [comment]
Implemented for v3.2.3

Three levels are exposed via `INPUT_DESKTOP_IGNORE_RESERVED_KEYS_LEVEL`:
0 = Anything goes
1 = Alt + Meta are ignored
2 = Alt + Meta + loads of other stuff are ignored

This macro defaults to `2`.

Exactly what is/isn't ignored can further be customised with `input_ignore_key_add()` and `input_ignore_key_remove()`
