### ISSUE TITLE
Block/Ignore Backspace and Escape when using Gamepad on Android

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#52]
Prior to most recent kernel these keycodes are fired by the default gamepad treatment in duplicate to button codes. Backspace on secondary face button (eg Xbox B, PS Circle) and Escape on meta button (eg Guide/Home). Prevent input source change on these keys when gamepad is enabled, and block them from binding, if appropriate.

**Comment by JujuAdams** [comment]
Is it worth outright blocking source swaps based on keyboard input altogether on mobile?

**Comment by offalynne** [comment]
keyboard Just Works on android so in Our Royal Opinion no, but you can go that way if you’re so inclined. the main hardware/software buttons send keycodes as well the TRRS button, which the implementer might want to make use of, excluding them from input isn’t the worst idea if it’s out of scope, just be sure to make note in source

**Comment by JujuAdams** [comment]
Fair, I'll do this at the same time as #51

**Comment by JujuAdams** [comment]
Not 100% on how to implement this. As mixed keyboard+gampead input is not currently supported, Input won't listen for keyboard events for a given player unless that player specifically has their input source set to `keyboard`. If a player is using a gamepad then keyboard input is ignored, even when rebinding controls.

The only time Input will listen for keyboard events when a player is using a gamepad is in the hotswap and assignment functions. At the moment, Input is listening to keyboard+mouse input first to determine what input source is being used. I suspect by re-ordering the logic to treat gamepad input preferentially to keyboard input, the proposed feature is implemented.

Alternatively, I can block backspace and escape entirely on Android when any gamepad is connected... but this feels overkill.

**Comment by offalynne** [comment]
> re-ordering the logic to treat gamepad input preferentially to keyboard input

sounds perfect!

**Comment by JujuAdams** [comment]
Implemented for v3.2.3
