### ISSUE TITLE
Should we disable hotswap when scanning for bindings with a source filter enabled?

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#529]

**Comment by offalynne** [comment]
fixed mode from hotswap seems ok?

mixed and multidevice might need a look; source swap from m+kb to or from gamepad should reject in case of filter, but between gamepads should not (may already work this way)

**Comment by MichelVGameMaker** [comment]
Thanks from what I see:
When in hotswap.mode and filtering input_binding_scan_start() only on KeyBoard+Mouse, the scan will stop if you use Gamepad (I guess it return an error code). I would have expected that the scan would just ignore input from gamepads when filtered on KB+M

When in mixed mode, it "works". Filtering input_binding_scan_start() only on KB make the scan not react to Gamepad.

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/9977f4ad0f25ff444f51d4fc025f6ff5964d9d77
