### ISSUE TITLE
Input returns true for the first x frames at the start of game when calling input_check(verb, 0, x)

### ISSUE THREAD

**Issue by tristanssun** [offalynne/Input#54]
Calling input_consume(all) after initializing inputs fixes this issue. See attached files

[bug_report.zip](https://github.com/JujuAdams/Input/files/6003040/bug_report.zip)

**Comment by JujuAdams** [comment]
Thanks for yoir bug report, I'll take a look when I get a chance

**Comment by JujuAdams** [comment]
Fixed in v3.2.3. The specific fixes are [here](https://github.com/JujuAdams/Input/commit/6e30f9275ca7d014c46e5778ef1737d484952d1a) if you'd like to implement them yourself ahead of 3.2.3 being released.
