### ISSUE TITLE
Changing room skips a tick

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#541]
> *put `input_tick()` in a Begin Step event that fires right at the start of the frame [highest object depth value]
there is no way to tell a time source to run between the Post-Draw and Begin Step events, which is what is needed
until we're able to bind struct methods to events there is no solution*

**Comment by offalynne** [comment]
Once we've got https://github.com/JujuAdams/Input/issues/445 and a YYG feature for *"bind[ing] struct methods to events"* this solvable

**Comment by JujuAdams** [comment]
We can work around lack of event binding with a trick I used for Snitch:

1. Create a persistent object inside the library. Put the tick function in its Begin Step event and whatever else we need
2. Create a time source that manages the instance
3. The time source creates an instance of the object once. If the instance has been destroyed, the time source throws an error (or alternatively recreates it)
4. Similarly for deactivation

Does this solve the issue?

**Comment by offalynne** [comment]
neato -- i think so ? would need to test of course. repro for the user report i believe was getting "true" on a momentary check twice (both before and after room change) needing an Object is obviously a little ugly but if it works !

**Comment by JujuAdams** [comment]
Yeah not ideal but perhaps a good enough hack.

**Comment by JujuAdams** [comment]
Implemented that on the v6 branch. Over to you for testing!
