### ISSUE TITLE
Input_binding_scan_set_params ignore array doesn't prevent gp_axis to register

### ISSUE THREAD

**Issue by ColoredCrow** [offalynne/Input#549]
Hello !

I've been told to write it down here, but unless I did it wrong, when using Input_binding_scan_set_params and the ignore array, I've been able to exclude succesfully the pad for exemple, but I couldn't prevent the joysticks from registering using gp_axislh, gp_axislv etc

**Comment by offalynne** [comment]
Seems to work OK per  `obj_test_rebinding_ignore_and_allow`

**Comment by JujuAdams** [comment]
Fixed by PR #551
