### ISSUE TITLE
Improve WUP-028 support

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#558]
Per [Dolphin Wiki](https://wiki.dolphin-emu.org/index.php?title=How_to_use_the_Official_GameCube_Controller_Adapter_for_Wii_U_in_Dolphin)

- [x] [Windows Massive Wii U GCN USB Driver (vJoy)](http://m4sv.com/page/wii-u-gcn-usb-driver)
- [x] ~~[Windows Dolphin Zadig Driver](https://wiki.dolphin-emu.org/index.php?title=How_to_use_the_Official_GameCube_Controller_Adapter_for_Wii_U_in_Dolphin#Windows)~~ Dolphin only
- [x] ~~[MacOS GCAdapterDriver](https://github.com/secretkeysio/gcadapterdriver)~~ Dolphin only
- [x] [Linux wii-u-gc-adapter](https://github.com/ToadKing/wii-u-gc-adapter)

**Comment by JujuAdams** [comment]
Is this all handled now?

**Comment by offalynne** [comment]
Yes
