### ISSUE TITLE
Modularise the library

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#574]

**Comment by offalynne** [comment]
Components
- Input binding
- Device type support
    - Mouse and keyboard
    - Gamepad
        - SDL2 gamepad mapping
        - Steamworks extension
    - Touch and virtual controls

**Comment by offalynne** [comment]
- Basic: direct checkers only
- Core: player and verb config
- Gamepad mapping: SDL2 mappings (requires Core)
- Gamepad extended: vibration, color, gyro (requires Core)
- Touch (requires Core)
