### ISSUE TITLE
Extended steamworks support

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#58]
> could you make a brief issue for that?

interface wishlist:
GetInputTypeForHandle (already in?)
SetLEDColor
TriggerVibration
~~ShowGamepadTextInput
GetEnteredGamepadTextLength
GetEnteredGamepadTextInput~~

**Comment by JujuAdams** [comment]
Not gonna do the OSK as part of Input, but I am going to look at making a separate library for it at some point
