### ISSUE TITLE
Bindings not found in 2023.1 running on YYC

### ISSUE THREAD

**Issue by nuevocharrua** [offalynne/Input#581]
![Captura de pantalla 2023-02-01 a la(s) 09 02 43](https://user-images.githubusercontent.com/24524075/216038127-bbe0054f-60e1-45ba-b16f-34d1dc76f4b6.png)

When opening a project in the new version 2023.1, when trying to run it on macOS YYC, the game does not run because it cannot find the bindings.

**Comment by JujuAdams** [comment]
I'm led to believe that 2023.1 has issues with YYC in general. I will wait for a hotfix for those issues before testing this.

**Comment by JujuAdams** [comment]
Half a dozen people have reported this so @TabularElf and I figured out a couple workarounds: https://github.com/JujuAdams/Input/commit/54681489d6cac6aeefac0d04baaf55dacadbf0ea   Will be in Input 5.5, or you can implement the fix manually if you can't wait.

**Comment by nuevocharrua** [comment]
It works fine, thank you 😃

**Comment by JujuAdams** [comment]
Workaround active for 5.5
