### ISSUE TITLE
If GUI size greater than window size, cursor coord space is incorrect

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#602]
Results in cursor drift on mouse capture. Easy to reproduce with test case by setting initial game window to larger than monitor height, which will result in GUI height greater than window height

If this is not fixable/worth fixing perhaps handle in `__input_release_multimonitor_cursor`, rename appropriately

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/c511841abf39f80ee74f8accc360e69f667fdcea
