### ISSUE TITLE
Per player gamepad type override

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#607]
and simple type macros

> probably want to save/load that with the rest of the input system state

**Comment by JujuAdams** [comment]
getter/setter + implementation: https://github.com/JujuAdams/Input/commit/bc3d66973a8dfebed069838cfd41e365a4a24a50

de/serialization: https://github.com/JujuAdams/Input/commit/03e0b4b2f6fd2d106cc906ad370f0c06f4a4da96
