### ISSUE TITLE
Should `INPUT_KEYBOARD_TYPE` return `keyboard` on Android for Chromebook only ?

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#616]
Android phones with physical keyboards are long out of support and IOT devices with keypads like smart TVs like to false-report `true` for the `PHYSICAL_KEYBOARD` system variable when in fact they use a virtual keyboard for text entry. should this check be for form factor (ARC/Chromebook) instead ?

**Comment by JujuAdams** [comment]
I'd say yes.

**Comment by JujuAdams** [comment]
#618
