### ISSUE TITLE
`INPUT_POINTER_TYPE`

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#619]
We have the nice constant `__INPUT_TOUCH_PRIMARY` to decide whether to *do touch* or *do mouse* stuff internally.

Since *doing touch* or *doing mouse* stuff involves a bit more hands-on from the library user beyond initial setup than keys or buttons, perhaps a constant similar to this value should be public, eg. `INPUT_POINTER_TYPE` (probably independent from `INPUT_TOUCH_IS_MOUSE`, this is implementation semantics). 

Beyond pointer implementation differences, this might be useful information for device-specific interface language eg. *click*, *touch*, *press*.
 
A reason we might not want to do this is to encourage a check to player source instead, since *player using touch* is a similar test to *player using gamepad*.

**Comment by JujuAdams** [comment]
Where would the prospective library use `INPUT_POINTER_TYPE` to control behaviour? I'd imagine mostly around cursor handling.

**Comment by offalynne** [comment]
library doesn't need to, just `mouse`, `touch`, or `none` for library user

**Comment by JujuAdams** [comment]
Sorry, *"prospective library user use" i.e. what's a use case

**Comment by offalynne** [comment]
Basically any case that precludes knowing the active source.

1. > device-specific interface language eg. *click* vs *touch* vs *press*

2. Selective display of "mouse" category on per-device rebind screen

3. Tailoring cursor-reactive behavior depending on pointer type (eg. whether to draw a cursor icon, whether to indicate a hover state)

**Comment by offalynne** [comment]
Merged, add docs

**Comment by offalynne** [comment]
https://github.com/JujuAdams/Input/commit/6fa5f5705ff1213b0219c7cf23cc50033e665c46
