### ISSUE TITLE
Normalize vibration

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#628]
Right now there's a macro for Switch platform vibration scale specifically but we can (and probably should) normalize vibration per motor, per device, per platform as with button mapping, gyro scale etc.

**Comment by JujuAdams** [comment]
Do you want a config script for this in a similar vein to icons?

**Comment by offalynne** [comment]
findings:
- everything is generally OK
- the Joy-Con Problem does not impact Switch Pro controllers
- it does impact Joy-Cons through Steam
- ~~Steam Controller also needs damping (same motors as Joy-Cons, same nasty buzz)~~

necessary changes:
- change `INPUT_VIBRATION_SWITCH_OS_STRENGTH` to `INPUT_VIBRATION_JOYCON_STRENGTH`
- ~~add `INPUT_VIBRATION_STEAM_CONTROLLER_STRENGTH` (default value 0.5)~~

**Comment by offalynne** [comment]
#630
