### ISSUE TITLE
Simplify gamepad types

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#641]
add config macro to trim down first-class gamepad types for normies and add some new ones for sickos

existing simple types to remove when `false`
- SNES (alias to Switch)
- N64 (no alias -- unknown/fallback)

new/additional simple types when `true` (some labels/features mismatch their current aliases)
- Steam Deck
- Steam Controller
- MFi
- 8BitDo
- Stadia
- Luna
- Atari VCS

etc.

**Comment by JujuAdams** [comment]
Where do Saturn pads see use these days? Still big in the fighting game community?

**Comment by offalynne** [comment]
Didn't toss Saturn or GameCube mainly because of mapping format-weirdness. Amenable to tossing if you prefer

- [37 devices in db](https://github.com/JujuAdams/Input/blob/community-data/community_gamepad_type.txt#L85-L122)
- SDL prescribes [Hori's layout](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/mapping_guide.png), so Xbox fallback comes out a bit weird (not the end of the world)

**Comment by offalynne** [comment]
Mmm yeah, squashed Saturn https://github.com/JujuAdams/Input/commit/029f55cc5598f88656e0b2f44bd51c61f4c61bbc

**Comment by offalynne** [comment]
Could get a little-further creative and squash GameCube as well if desirable by rearranging face button mappings on SDL2 platforms per gamepad type so they alias to Switch labels correctly (will have to wait a few weeks so I can proof with relevant gamepad hardware)

**Comment by JujuAdams** [comment]
I think GC is gonna be something the fighting game crowd will want to support in detail so I'm happy to leave that in there.

**Comment by offalynne** [comment]
Good 2 merge, then
