### ISSUE TITLE
input_gamepad_find_in_sdl2_database - undefined value when controllers are plugged in

### ISSUE THREAD

**Issue by DragoniteSpam** [offalynne/Input#66]
One or more variables hasn't been defined, it seems.

    Input: Gamepad 0 connected
    Input: New gamepad = "XInput STANDARD GAMEPAD", GUID="none"
    ERROR!!! :: ############################################################################################
    ERROR in
    action number 1
    of  Step Event0
    for object World:
    
    
    DoAdd :1: undefined value
     at gml_Script___input_gamepad_find_in_sdl2_database (line 20) -         if (is_struct(_os_vid_pid_dict) && variable_struct_exists(_os_vid_pid_dict, vendor + product))
    ############################################################################################
    gml_Script___input_gamepad_find_in_sdl2_database (line 20)
    gml_Script___input_class_gamepad (line 191) -     __input_gamepad_find_in_sdl2_database(self); //Also sets gamepad description
    gml_Script_input_tick (line 87)
    gml_Object_World_Step_0 (line 8) - input_tick();

Happens with my [Xbox 360 controller](https://www.ebay.com/p/1301673785), [Xbox One controller](https://www.bestbuy.com/site/powera-enhanced-wired-controller-for-xbox-series-xs-mist/6434399.p?skuId=6434399), and whatever model of the DualShock 3 is that came with the PlayStation, but it's fine when it's just the mouse and keyboard.

This seems to be new in 3.3.2, although I skipped 3.3.1 and when I went back to check it had another bug that was causing it to fail, so I'm not exactly sure where this was introduced. 3.3.0 was fine.

**Comment by JujuAdams** [comment]
Hiya, thanks for reporting this bug

On reviewing the code I don't understand why this crash is happening (both `vendor` and `product` should be strings) or why this would suddenly become a problem after 3.3.0 as no relevant code has been touched.

Could you step through `__input_class_gamepad()` for me please? You might need to drop in some `show_debug_message()` calls to debug certain values

**Comment by JujuAdams** [comment]
Potentially found a fix: https://github.com/JujuAdams/Input/commit/5fe19edb2b522783fcd55e5b891909761b30964e

If you could implement this yourself and test that'd be appreciated. Fix will otherwise be available in 3.3.4

*(Please reopen this ticket if this fix doesn't address the problem)*

**Comment by DragoniteSpam** [comment]
So this is awkward, but... when I tested the 3.3.2 release just now, the crash didn't occur. Not sure if the runtime update from a few days ago affected something that Input does internally, or what.

In any case the change made in that commit is functional, and my gamepads work as expected.

¯\\\_(ツ)_/¯

**Comment by JujuAdams** [comment]
¯\\\_(ツ)_/¯
