### ISSUE TITLE
Add inverted look player setting (flip cursor y)

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#674]

**Comment by JujuAdams** [comment]
Great call, though I think we'd flip the cursor delta-y rather than the y-axis itself?

**Comment by offalynne** [comment]
@dragoniteSpam pointed out in DM during 3d camera tests while firming up gyro stuff that it is somewhat (more than i expected) common for games to map camera pitch 1:1 to 'mouse y in viewport' since unlike yaw, pitch should naturally cap out (sky/ground) so maybe we need to invert the axis itself ? i defer to him here...

**Comment by DragoniteSpam** [comment]
pretty much; when I invert a camera axis myself i generally just throw a negative sign in front of the mouse/gp axis delta, so if you wanted to hard-wire that into Input i'd assume that's the way you'd want to do it here too

i don't actually remember how I've seen other people implement camera inversion but i can't imagine most people would do it differently, since inverting the delta is pretty straightforward

**Comment by offalynne** [comment]
ok delta it is !

**Comment by offalynne** [comment]
did the boilerplate but implementation eludes me https://github.com/offalynne/Input/commit/66dba6bff4f6de00820b6ae452e8f944e6584b4d i do not think dy alone will do the trick TvT

**Comment by JujuAdams** [comment]
When do we want to invert the cursor?

Suggestion:
1. When using gamepad thumbstick (and virtual thumbstick by extension)
2. When using keyboard to move cursor
3. When using locked mouse

Do we want inversion when using unlocked mouse?

**Comment by offalynne** [comment]
I believe we should support mouse unlocked at least functionally since "lock can be blocked", though I don't think it makes much use-case sense unless lock is intended

**Comment by JujuAdams** [comment]
Yeah mouse unlocked case is definitely tricky. I will 🧠 on it

**Comment by offalynne** [comment]
i think mmm-maybe this plus #675 means a light rework of where coord space info is fetched and applied per the cursor update stufff. in any case you've already worked out most of the hard stuff for that purpose (i believe)

**Comment by JujuAdams** [comment]
https://github.com/JujuAdams/Input/commit/2385401b8ee209aa203e9f4c20f805bb9a845cd0

Basic "invert dy" method seems fine even when the mouse lock is blocked? What am I missing?

**Comment by offalynne** [comment]
Nothing! I was missing.. something!
