### ISSUE TITLE
Crash on iOS as soon as a gamepad is recognized

### ISSUE THREAD

**Issue by moppin** [offalynne/Input#69]
Seem to get this crash on the moment a gamepad becomes connected to iOS:
![image](https://user-images.githubusercontent.com/64902135/114844505-d0d42d00-9e15-11eb-9972-5c1d3f83b8af.png)

Discovered this when connecting a Backbone One gamepad to my iPhone 11 Pro Max to test my game out. If the gamepad is connected at the moment of launching the game, it crashes on launch. If the gamepad becomes connected while the game is active, it crashes on the moment the gamepad becomes connected.
Backbone is connected via Lightning but I was able to reproduce the same crash with a Xbox controller connected via bluetooth too for both cases. All of them give this same crash message.

**Comment by JujuAdams** [comment]
Thanks for getting in touch! I'll take a look at this now

**Comment by JujuAdams** [comment]
Related to #66?

**Comment by JujuAdams** [comment]
Fixed in private repo
