### ISSUE TITLE
Verb not recognised

### ISSUE THREAD

**Issue by jgedri** [offalynne/Input#70]
I want to follow the quick-start guide, but keep getting "verb not recognised" errors.

`/// Step event
if (input_check(eVerbs.Left)) x -= 3;
if (input_check(eVerbs.Right)) { x += 3 };
if (input_check(eVerbs.Up)) y -= 3;
if (input_check(eVerbs.Down)) y += 3;

/// obj_input Create event
enum eVerbs
{
	Left,
	Right,
	Up,
	Down,
	Swing,
}

// Bind default keys to verbs
input_default_key(ord("A"), eVerbs.Left)
input_default_key(ord("D"), eVerbs.Right)
input_default_key(vk_up, eVerbs.Up)
input_default_key(vk_down, eVerbs.Down)

input_player_source_set(INPUT_SOURCE.KEYBOARD_AND_MOUSE)`

**Comment by OmegaX1000** [comment]
Do the error messages specify a specific verb that isn't being recognized?

**Comment by jgedri** [comment]
Yes, it doesn't like any of the verbs I've set up.

`
___________________________________________
############################################################################################
ERROR in
action number 1
of  Step Event0
for object obj_hero:

Input:
Verb not recognised (2)
 
 at gml_Script___input_error (line 389) -     show_error("Input:\n" + _string + "\n ", false);
############################################################################################
gml_Script___input_error (line 389)
gml_Script_input_check (line 38) -         __input_error("Verb not recognised (", _verb, ")");
gml_Object_obj_hero_Step_0 (line 5) - if (input_check(eVerbs.Up)) y -= 3;`

**Comment by OmegaX1000** [comment]
I copied the code you provide into an empty project and I got no errors (but I couldn't get the object to move but that an issue for another time). What version of input are you using? I was using v3.3.3 for my testing.

**Comment by jgedri** [comment]
I don't know. How do I find out?

**Comment by OmegaX1000** [comment]
Look for the Macro: __INPUT_VERSION at the top of __input_system script in your input folder.

**Comment by jgedri** [comment]
It's v. 3.3.3.

**Comment by OmegaX1000** [comment]
I manage to recreate the error by copying the code you provided into the create event (both the stuff below ///Step event and ////obj_input Create Event). Did you put your ///Step event code into the actual step event itself?

**Comment by jgedri** [comment]
Yes. I have two different objects, but that shouldn't be a problem.

**Comment by jgedri** [comment]
Does all the code need to be in one object?

**Comment by JujuAdams** [comment]
Hiya - no, the code doesn't need to all be in the same object.

What you've shared should be sufficient so there's likely another problem. Could you please check that `obj_input` is being created before calling your Step event code? Easiest way to do this is to put a breakpoint down in the Create event and run in debug mode.

Furthermore, you haven't mentioned where you're calling [`input_tick()`](https://github.com/JujuAdams/Input/wiki/Functions-(System)#input_tick). Could you confirm where you're calling that?

**Comment by jgedri** [comment]
Thanks for replying. Just to confirm: you want me to put a breakpoint in the Create event of `obj_input`? And I put `input_tick` in the Step event of that same object.

**Comment by JujuAdams** [comment]
Yep! Just to make sure that the Create code is being executed at the expected time

**Comment by jgedri** [comment]
> 
> 
> Yep! Just to make sure that the Create code is being executed at the expected time

How do I do that? I'm not very experienced at debugging.

**Comment by JujuAdams** [comment]
https://docs2.yoyogames.com/source/_build/2_interface/2_extras/debugging.html

https://youtu.be/iJH_uTq9iOQ

**Comment by JujuAdams** [comment]
Are you still having problems here?

**Comment by jgedri** [comment]
I'm getting a lot of "variable only referenced once" errors, but no "verb not recognised". So no.

**Comment by JujuAdams** [comment]
For future reference, it's good practice to close tickets if you're no longer having issues.
