### ISSUE TITLE
INPUT_TRIGGER_STATE enum assignments don't appear to be valid.

### ISSUE THREAD

**Issue by arzulo** [offalynne/Input#737]
Relevant docs: https://www.jujuadams.com/Input/#/6.0/Library-Constants?id=trigger-effect-states

In file `__input_macros.gml`  the enum is established 
https://github.com/JujuAdams/Input/blob/643cd727c5e6e391dcb1b90545a88b917de98b10/scripts/__input_macros/__input_macros.gml#L232
```
//DualSense haptic trigger effect states
enum INPUT_TRIGGER_STATE
{
    EFFECT_OFF               = ps5_gamepad_trigger_effect_state_off,
    EFFECT_FEEDBACK_STANDBY  = ps5_gamepad_trigger_effect_state_feedback_standby,
    EFFECT_FEEDBACK_ACTIVE   = ps5_gamepad_trigger_effect_state_feedback_active,
    EFFECT_WEAPON_STANDBY    = ps5_gamepad_trigger_effect_state_weapon_standby,
    EFFECT_WEAPON_PULLING    = ps5_gamepad_trigger_effect_state_weapon_pulling,
    EFFECT_WEAPON_FIRED      = ps5_gamepad_trigger_effect_state_weapon_fired,
    EFFECT_VIBRATION_STANDBY = ps5_gamepad_trigger_effect_state_vibration_standby,
    EFFECT_VIBRATION_ACTIVE  = ps5_gamepad_trigger_effect_state_vibration_active,
    EFFECT_INTERCEPTED       = ps5_gamepad_trigger_effect_state_intercepted,
}
```
However it appears none of the `ps5_` variables are set anywhere? 
Trying to reference any one of these enumerator values results in -1.

**Comment by offalynne** [comment]
These are GM constants

**Comment by JujuAdams** [comment]
Might be that these constants can't be used if a dev doesn't have a certain export target or subscription tier? If so, we should work around that.

**Comment by offalynne** [comment]
These are always available regardless of export/sub, they just show a warning in code IDE (as many other constants we use). No getting around using them *somewhere* for console support. Zane confirmed in Discord his was a Steam configuration issue and the constants are indeed available as tested: -1 is `EFFECT_INTERCEPTED`
