### ISSUE TITLE
6.0 version documention lists function that doesn't exist in 6.0.3

### ISSUE THREAD

**Issue by DrJammyGames** [offalynne/Input#739]
I'm working on rebinding my keys, but the 6.0 documention lists a function that isn't in the 6.0.3 version: https://www.jujuadams.com/Input/#/6.0/Functions-(Binding-Access)?id=binding_set 

input_binding_set lists that you should use input_binding_keyboard, but that doesn't exist. I'm not sure if I should use input_binding_key instead or if there was something else included in 6.0.3 that replaced it? Either way, I'm struggling a bit now on rebinding my keys.

**Comment by JujuAdams** [comment]
Thank you for reporting this. @offalynne has addressed the issue in documentation. `input_binding_key()` is the correct function name.

A word on version numbering: any version that looks like `6.0.x` will be compatible with 6.0 documentation. We only ever change what functions are available when we increment either the first ("major") or second ("minor") version numbers. Please see https://semver.org/ for more information on how version numbers work.
