### ISSUE TITLE
source_mode_set, documentation example incorrect

### ISSUE THREAD

**Issue by tshum101** [offalynne/Input#753]
in the example code, I believe the first line has a typo. 

**Currently:** input_source_mode_set(INPUT_GAMEPAD.FIXED)

**CHANGE TO:** inpute_source_mode_set(INPUT_SOURCE_MODE.FIXED)

Following the current example throws an error

**Comment by offalynne** [comment]
Fixed, please feel free to submit corrections directly as edits, if you are able: https://github.com/JujuAdams/Input/tree/docs/docs/6.0

**Comment by tshum101** [comment]
Sounds good. I see now that I can edit in github. Will doif I encounter future typos
