### ISSUE TITLE
input_check_pressed triggers multiple times

### ISSUE THREAD

**Issue by castorpollux285** [offalynne/Input#762]
Hello,

since upgrading from input 5 to 6 I have this issue: 

Example:
I have a Menu Room where I choose a menu item in Begin Step Event to go to the game room with 

`if input_check_pressed("accept")
{
// go to game room
}
`

And in the next room, I have this in obj_player Begin Step Event:

`if input_check_pressed("interaction")
{
// Do this
}
`

"interaction" and "accept" are both binded to vk_space in the config script.

And even when I only press space in the menu room, it is also triggered in the player object that is in the next room.
I did not have this issue with version 5.

**Comment by offalynne** [comment]
Please try using the Step event instead of Begin Step.

**Comment by castorpollux285** [comment]
That 

> Please try using the Step event instead of Begin Step.

That solved the issue. Thank you!
