### ISSUE TITLE
Unable to rebind XInput STANDARD GAMEPAD; Inputs are not detected during scanning.

### ISSUE THREAD

**Issue by Terrorbuns** [offalynne/Input#763]
Scanning for new input to rebind a key does detect inputs from XInput STANDARD GAMEPADs. 
It works fine for other controllers and the keyboard. 
The controller works fine with Input outside of rebinding.

Windows, tested on multiple projects and computers, used to work in 6.0.4, does not work in either 6.0.4 or 6.0.5.

Suspect it was a Windows Update that might've broken something.

**Comment by JujuAdams** [comment]
From Discord: Issue likely to do with drifting axis causing the device to never return "no input detected" before performing a proper scan. Solution is to set a higher axis threshold, or to allow ignored button/axes to affect "no input detected" state.
