### ISSUE TITLE
Return the error struct in input_system_verify if asked

### ISSUE THREAD

**Issue by nkrapivin** [offalynne/Input#769]
Sometimes it's necessary to know *what* exactly is corrupted in the bindings, but `input_system_verify` only returns true or false for now.
Perhaps an optional argument could do, `[returnErrorStruct=false]`.

**Comment by JujuAdams** [comment]
Complete for 6.1 https://github.com/JujuAdams/Input/commit/fa54c3428fbfda6c5dbca55f8ce1b878b2226ca1
