### ISSUE TITLE
Transform coordinate does not work with `camera_create`

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#771]
`camera_get_view_x`, `y`, `width`, `height`, `angle` always return 0 for `camera_create`d cameras

Camera properties should be retrieved with [`camera_get_view_mat`](https://manual.yoyogames.com/GameMaker_Language/GML_Reference/Cameras_And_Display/Cameras_And_Viewports/camera_get_view_mat.htm) if possible

**Comment by Hmmmpf** [comment]
This issue extends to any cursor related activities while the coord space is set to ROOM, as `camera_get_view_width` and `camera_get_view_height` are being used to determine pointer values in `__input_system_tick` , as well as boundary margins in `__input_class_cursor`, and `__input_class_gyro`
