### ISSUE TITLE
weird interaction with gamepad button and game_restart

### ISSUE THREAD

**Issue by roycerezendes** [offalynne/Input#780]
For some reason I don't understand when I use this code, my game restarts fine:

if(gamepad_button_check_pressed(0,gp_face4)){
	game_restart();
}

If all I change is this, it does not work fine and seems to do an infinite loop of restarting (as I can tell from the output window) and my game window is stuck and doesn't seem to be actually restarting infinitely at super speed  or anything, just frozen.

if(input_check_pressed("special")){
	game_restart();
}

all other gamepad inputs such as moving and firing and everything work fine with the input_check type code like for example right before this I have: (and it works fine)

if(input_check_pressed("cancel")){
	game_end();
}

**Comment by offalynne** [comment]
https://tabularelf.com/custom-game-restart/

**Comment by offalynne** [comment]
even though the builtin function is bad news this is still a bug so we'll look into it
