### ISSUE TITLE
Move gamepad value delta out of mapping class

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#784]
Currently only mapped gamepads handle delta correctly. This is noncritical but should be implemented so delta-dependent behaviour (eg. rebinding, source swapping) is the same for mapped and unmapped contexts.

**Comment by JujuAdams** [comment]
Recommend that unmapped gamepads spin up an instance of the class and use some sort of pass-through behaviour.

**Comment by offalynne** [comment]
Per Juju's remarks we should just remove all the "unmapped" branching and create a mapping in all scenarios
