### ISSUE TITLE
weird bug but i fix it...

### ISSUE THREAD

**Issue by ghost** [offalynne/Input#787]
Hey JujuAdams i just updated Input to the latest version (6.1.2)
then i run my game normally and i got no error message it just said build failed
so i started with `__input_initialize` i found this at line 89 `ref_create({});`
i don't know what is that exactly but i just commented it and run the game again and yeah its working.

_ofcourse after i cleaned the game and restarting the program..._(;

**Comment by JujuAdams** [comment]
What version of GameMaker are you using?

**Comment by ghost** [comment]
Latest Version of GMS2 not beta
EDIT: Here the details -> IDE v2023.8.1.102 Runtime v2023.8.1.148

**Comment by offalynne** [comment]
Unable to reproduce on IDE v2023.8.1.102 Runtime v2023.8.1.148 🤷‍♀️

**Comment by ghost** [comment]
Ok its fine :D
