### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by ghost** [offalynne/Input#793]
I'm attempting to debug my game, but when I try all that appears is the line _input_system_tick();

Is there a way to debug my game while using Input?

<img width="1440" alt="Screenshot 2023-10-03 at 8 05 00 PM" src="https://github.com/JujuAdams/Input/assets/146897904/e1c95b11-a199-4572-89ff-9c5d1bf77c12">

**Comment by JujuAdams** [comment]
This is unrelated to Input. All that's happening here is that this is where the game happens to be stopping when you hit the pause button in GameMaker's debugger. You can still debug the rest of the game as you normally would. If you want to step out of this particular function, press F10 on your keyboard.

You can learn more about GameMaker's debugger here: https://gamemaker.io/en/tutorials/debugger  https://www.youtube.com/watch?v=iJH_uTq9iOQ
