### ISSUE TITLE
Improve debug draw visuals for virtual buttons

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#800]

**Comment by arzulo** [comment]
Hey Juju!
Did you have a vision for what it is you wanted to enhance about the debug draw for these?

I have a bit more free time now and I've been poking around in the vbutton source recently so I'd be more than happy to help with this if you had some direction. Just let me know!

**Comment by offalynne** [comment]
@JujuAdams are the example/test objects indicative of what you want (showing vector arrows, etc) ?

**Comment by JujuAdams** [comment]
Didn't have anything particular in mind other than "they're kind of basic at the moment". I think it would be good to be able to see touchpoints and vectors, but I hadn't given the specifics much thought beyond that.
