### ISSUE TITLE
Provide Dpad presentation hint as Gamepad struct field after gamepad type is ID'd & aliased

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#81]
dpad style hint to assist platform-correct iconography selection per TCR/TRC/LotCheck requirement

something like `dpad_style`
csv below. data is simple, probably safe to hardcode
```
cross,default
disc,steam,xbox 360,saturn,ouya,
segments,psx,ps4,ps5,
buttons,switch joycon pair,
stick,switch joycon left,switch joycon right,
```

**Comment by JujuAdams** [comment]
I think is valid, yep, since showing the correct dpad icon is a compliance requirement. Gonna hardcode it!

I'm a bit wary about dpad=stick for Switch single joycon because I'm not 100% sure how Input handles the "dpad" on single joycon at the moment. I'll have to check.

**Comment by JujuAdams** [comment]
Implemented for v3.4.0, and created an issue for me to check Switch dpad-on-stick behaviour (#84)

**Comment by offalynne** [comment]
To perhaps clarify a bit, reasoning behind dpad-stick overlap maps for Saturn, SNES, and Joycon Single is user should be able to optionally override/force a gamepad type (see PSO2, Death Stranding, etc for example) to overcome devices spoofing a different pad (eg. retrobit and 8bitdo compatibility modes), or software virtual controllers (Steam, Vigem, ReWASD, etc) in which case Dpad or stick may be mapped as each other on pads types that have only one.

**Comment by offalynne** [comment]
> I'm a bit wary about dpad=stick for Switch single joycon because I'm not 100% sure how Input handles the "dpad" on single joycon at the moment. I'll have to check.

Yeah "stick" is wrong and can be omitted
 https://github.com/JujuAdams/Input/blob/master/datafiles/sdl2.txt#L156-L159

**Comment by JujuAdams** [comment]
GM natively interprets thumbstick movement as dpad button presses so that's probably the source of confusion.
