### ISSUE TITLE
Harden per-platform keyboard label identification

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#82]
Cross platform testing! 🥳

**Comment by JujuAdams** [comment]
Ready to test with new `keyboard_lastchar` behaviour on `dev` branch.

**Comment by JujuAdams** [comment]
Is this solved now on `dev`?

**Comment by offalynne** [comment]
Just want to confirm all's well on relevant platforms (Win/Mac/Linux/Android), haven't yet

**Comment by offalynne** [comment]
android's going to be a Whole Thing and i need to give AZERTY a bit of polish but #96 gets things where i want them at for now 🏋️‍♀️
