### ISSUE TITLE
Calling window_set_size breaks multitouch on mobile HTML5

### ISSUE THREAD

**Issue by murraya2** [offalynne/Input#820]
Normally, multitouch works on mobile HTML5. However, if I rescale the game canvas using window_set_size, it no longer works. The buttons continue working fine on their own in isolation, but two buttons cannot be pressed at the same time.

Demo running live: https://andrfw.itch.io/input-multitouch-bug-report 
(password is `inputbugreport`)
Going to this on a mobile and trying to hold the dpad with one finger and press the button with another should show the issue.

Demo project: https://drive.google.com/file/d/1bP-NSB8yG5KL_wJVUoOsbyBr0D_1HhM2/view?usp=sharing
Note that the object `oDemo` has a comment in its Create event that shows the line that is causing the issue (without them things work as intended, but the screen doesn't scale).

I have, unfortunately, _not_ tested this on native android/iOS, since I don't own those exports. It's possible this is a more general bug than HTML5, but I cannot test that at this time.

**Comment by JujuAdams** [comment]
What version of GameMaker are you using? What version of Input are you using? What browser / browser version are you testing on? Not that we'd necessarily expect this, but have you confirmed that multi-touch works natively in GameMaker after using `window_set_scale()`?

**Comment by murraya2** [comment]
Thanks for the fast response!

Here are my testing versions:
* Gamemaker:
  * LTS (2022.0) for the sample project linked above
  * 2023.8.2.106 for the original project where I noticed this
* Input: 6.1.2
* Browser: Chrome 118 on Android 13

I haven't checked if native gamemaker multi-touch has the same bug, I can do that later today!

**Comment by JujuAdams** [comment]
cool cool cool if you could check native GM too that'd be great.

**Comment by murraya2** [comment]
I've confirmed that normal GM multitouch (via `device_mouse_x_to_gui` and `device_mouse_y_to_gui`) is working as expected. I updated the demo to have a "swap demo" button that takes you to a demo that executes the exact same screen scaling code but uses non-input multitouch.

Here's the new yyz: https://drive.google.com/file/d/1aU-JCcZOrxFnP89RwV2BmsWUc5CpV1P4/view?usp=sharing

The itch link in my original post has been updated to be running this new version.

Also I dug into the Input virtual button code a bit and... it really does seem like everything is set up right! It even uses `device_mouse_x_to_gui` and `device_mouse_y_to_gui`, which is what I confirmed was working. Very confused, hoping someone can make sense of it 🤞

**Comment by arzulo** [comment]
Looking at this right now. Just to fill in some detail of what I see when using the demo.

It's not that the multitouch _**isn't**_ working on HTML, it is recording multitouch still and the buttons are able to be pressed simultaneously.  
However, what I'm seeing is any touch after the 1st is being recorded in a different location. For example, in this demo when holding the dpad (upper left vbutton), the button's (lower right vbutton) is pressable by touching the bottom right corner of the screen.  

This is confirmed by the second menu of the readouts of the touch x/y values. 

So some scaling business going on...

**Comment by murraya2** [comment]
Ahhh good find!! Thank you for taking a look at that. If that's the case then this actually _does_ point to an upstream bug in gamemaker. I checked the HTML5 runtime (yay it's open source now!) and found the following code. It does seem that device zero is handled in a completely different code path than the rest. They're both running through the same scaling code a few lines down, but the fact that they're separate does raise a red flag when combined with what we're seeing. I'll make a trimmed down version of the demo project (with _just_ the second menu) and file an issue over on the HTML5 runtime repo.

<img width="731" alt="image" src="https://github.com/offalynne/Input/assets/23423061/bff6f1fe-44ee-4635-a525-e4cd512f5337">

Thanks again so much @arzulo!!!!

**Comment by murraya2** [comment]
This has been resolved in this PR: 
https://github.com/YoYoGames/GameMaker-HTML5/pull/333

Also, just wanted to report that due to this and some other changes to the HTML5 runtime, the Input + HTML5 mobile experience is _VERY GOOD_ now! 

closing this issue out, thanks again for the help everyone <3
