### ISSUE TITLE
Macro-optional blocking of IME, Alt (Windows, Linux) and Meta (Mac) buffer dump and related key sticking bugs

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#83]
Investigate if possible/practical. Seemed doable last I poked.

**Comment by JujuAdams** [comment]
We've got key blocking implemented already on the binding side, what else dya think needs doing?

**Comment by offalynne** [comment]
keyboard_check, lastkey, and lastchar are all impacted by pretty heavy alt key bugs on win/linux and meta key on mac. the frame on (or after, depending) the problematic modifier key is *released*, other bad things happen (other keys stick, buffer dumps a bunch of ghost presses at once, etc). the current blacklist on known-problem keys is good and gets us a good part of the way there, this proposed filter (optionally?) catches and fixes the rest.

**Comment by JujuAdams** [comment]
Ah I see, what would the filter contain?

**Comment by offalynne** [comment]
good Q, will add notes when i got em

**Comment by offalynne** [comment]
while poking #82 I had a look at this and most of my concerns are put to rest; Input's binding methodology avoids pitfalls around keycombo input, altkey strings and IME issues. there do seem to be some problems with binding occasionally sticking in 'state 1' (waiting for key release) but this is potentially a different problem and i'll spare further speculation till i've tested the behaviour more thoroughly
