### ISSUE TITLE
Feather finding all lint errors

### ISSUE THREAD

**Issue by dgreene1** [offalynne/Input#830]
### Expected:

- The lint errors in Input will not show up because they have been disabled

### Actual Results:

- I see hundreds of Feather warnings (note I have feather strict mode on)

### Solution:

Change every reference of `// Feather disable` to `// feather disable`

**Comment by JujuAdams** [comment]
We don't support Feather and we won't for the forseeable future.

**Comment by dgreene1** [comment]
Hi @JujuAdams. I apologize for not providing clear enough information.

I’m not asking for you to support Feather—I’m asking to make it so Input’s internals don’t get searched by Feather.

What I mean is that the Feather findings inside Input show up in the consumer’s Feather because of the F is supposed to be lower case f.

So what I’m asking for is permission to submit a PR where I have changed every reference of `// Feather disable` to `// feather disable`.

This one time fix will save myself and every other consumer from having to find-all-replace on the Input folder every time we install an updated version of Input.

**Comment by JujuAdams** [comment]
Type sensitivity is a GameMaker bug. Not our problem.

I have spent 18 months waiting for YYG to get Feather into a place where it's usable. It isn't. I'm not going to spend any more of my time working around their mistakes.

**Comment by dgreene1** [comment]
For those looking for a workaround, apparently you can add a file to the Input folder and inside of it add

```
// feather ignore all in ./*
```

There’s also a way to ignore any file by supplying the path.

> Type sensitivity is a GameMaker bug. Not our problem.

I understand what you’re saying, but the current code doesn’t use what they’ve documented ( https://gms.yoyogames.com/ReleaseNotes.html ). **Update**: my workaround won’t work until the next Gamemaker release since… their feather implementation has a bug in it that ignores the ignore statements. 🤦‍♂️ 

> I have spent 18 months waiting for YYG to get Feather into a place where it's usable. It isn't. I'm not going to spend any more of my time working around their mistakes.

In my limited time, I’ve found that it works ~pretty well~ fine if you do things exactly like it wants you to. So yes, there are some times where it has some false or chatty alerts and those can take time away from valuable projects. Speaking of which, I don’t want to take anymore of your valuable time.

Since I found a workaround I’ll move on. I was and am happy to make the update in the code if you change your mind. I love contributing to open source, especially great libraries like the one you provide @JujuAdams. :)

Thanks again for the work that you do to help make Gamemaker a productive and multi-platform experience. The existence of your plugins are part of what help me feel comfortable using Gamemaker. :)
