### ISSUE TITLE
Input 6.2.1 beta: input_controller_object depth has been changed (expected 16001, got 0)

### ISSUE THREAD

**Issue by PeterKazimir** [offalynne/Input#833]
Hi. I am new to Gamemaker so I am starting off with Hero's trail template and I wanted to add the Input library to it.

This is not necessarily an Input library bug, but I would still love to understand what is going on so I can avoid it during further game development.

I get this error after I enter the first room:

...
PS5 controller recognized here...
...
Input: Hotswapping on mouse button press
Input: Setting player 0 profile to "keyboard_and_mouse"
ERROR!!! :: ############################################################################################
ERROR in
action number 1
of Create Event
for object obj_pillar_fallen:

Input 6.2.1 beta:
input_controller_object depth has been changed (expected 16001, got 0)
Please ensure that input_controller_object is never manually created and depth is not manually set
 
 at gml_Script___input_error (line 14) -         show_error("Input " + __INPUT_VERSION + ":\n" + _string + "\n ", false);
############################################################################################
gml_Script___input_error (line 14)
gml_Script_anon___input_initialize_gml_GlobalScript___input_initialize_4072___input_initialize_gml_GlobalScript___input_initialize (line 207) -                 __input_error("input_controller_object depth has been changed (expected ", __INPUT_CONTROLLER_OBJECT_DEPTH, ", got ", input_controller_object.depth ,")\nPlease ensure that input_controller_object is never manually created and depth is not 

However, when I create an empty room with some tiles and obj_player, I don't get this error.
Can it be related to the depth spacing, perhaps? No idea.

Thanks!

**Comment by offalynne** [comment]
The error tells you exactly what you need to know, there's no way I can think to better explain the error to you than the message you have pasted here. If reading the error message given the situation you presented is not adequate information for you to solve the problem, perhaps the library is a bad fit for your needs. Otherwise, please follow up with what steps you have tried to address the error, and the outcome of what you have tried, so we are able to help!

**Comment by PeterKazimir** [comment]
Hi, I found the script that changes the depth of all instances, so I excluded input_controller_obj from that change. You are right, the information was there, I just need to gather more experience. Have a great day!

**Comment by offalynne** [comment]
Glad to hear it! `depth = -y` is a common enough pattern that we can standardize on that perhaps, since the controller object's position is otherwise insignificant.
