### ISSUE TITLE
On Linux, launching the game with Steam but with Steam Input disabled causes the game to instantly crash

### ISSUE THREAD

**Issue by TailfeatherStudios** [offalynne/Input#839]
IDE: 2023.11.1.129
Input version 6.1.5 (also tried 6.2.1 beta)

I'm experiencing a bug where launching the game with Steamworks enabled but Steam Input disabled causes the program to instantly close. I can't even get a single frame, so I'm unsure of how to debug it. I can't even playtest because of a bug that renders the Steamworks APIs unreachable, and are therefore not loaded. With Steam disabled, the game works. Launching the game with Steam Input enabled also works.

Update: I've tried setting INPUT_ALLOW_STEAMWORKS to false, and that still didn't fix it. Also, this bug happens on the Steam Deck too.

**Comment by offalynne** [comment]
Please test a project ***with the Steamworks extension*** and ***without Input*** to confirm the issue is with Input and not the Steamworks extension

**Comment by TailfeatherStudios** [comment]
The project originally didn't use Input -- it used the native Game Maker commands, and it worked. Attached is a Linux
 build of my game created before Input support was implemented: [onu181223bII_l.zip](https://github.com/offalynne/Input/files/13724477/onu181223bII_l.zip)
 
 In any case, if you'd like me to create a new project with the requirements you specified, let me know.
(If you get the error "Steam init failed!" then try adding it to Steam as a non-Steam game.)

**Comment by offalynne** [comment]
> if you'd like me to create a new project with the requirements you specified, let me know

Yes, please

**Comment by TailfeatherStudios** [comment]
You've probably already seen in the Discord, but the problem is in fact Input related. Here's the new project I used:
[Blank.zip](https://github.com/offalynne/Input/files/13724935/Blank.zip)

If there's any way I can troubleshoot this, I'll let you know.

**Comment by TailfeatherStudios** [comment]
Closed - may not be input related after all, need to do some more troubleshooting

**Comment by TailfeatherStudios** [comment]
It appears that this IS in fact Input related. The error logs show that an erroneous variable, _default_xbox_type, is not defined. In fact, this variable is only used in this one instance. See the images below. I'd fix it myself, but I don't know what _default_xbox_type is supposed to be.
![20-12-2023_04-43-55_GameMaker_e1548](https://github.com/offalynne/Input/assets/109933922/029b275d-dab8-4da1-9c66-35677ddacb5b)
![20-12-2023_04-47-06_GameMaker_33e32](https://github.com/offalynne/Input/assets/109933922/68eef2b1-36a9-437a-98eb-173a0b80be67)

**Comment by offalynne** [comment]
Regression from ee08eba148a0ddf5b6d59f2882b7aafe6af7b9a7
Fixed by 5024d71475528075690f4d7497a1d9d093432e50
