### ISSUE TITLE
Where do I put the definition of the combos?

### ISSUE THREAD

**Issue by MattKYT** [offalynne/Input#840]
Do I put it where I define the verbs? or does it go in the object where I am executing the actions? I did that last thing and it gave me the error that there was already a combo with that name (even hitting the keyboard gave me that error)

**Comment by offalynne** [comment]
> Where do I put the definition of the combos?

Wherever you like

> does it go in the object where I am executing the actions

Sure

> it gave me the error that there was already a combo with that name (even hitting the keyboard gave me that error)

Please download and refer to the example project if you need further help 
https://codeload.github.com/offalynne/Input/zip/refs/heads/master
