### ISSUE TITLE
Wording error in the documentation

### ISSUE THREAD

**Issue by indieklem** [offalynne/Input#848]
In think there is an error in the documentation (https://offalynne.github.io/Input/#/6.1/Functions-(Players)?id=players_get_status) of the function `input_players_get_status()`.

It is written: 
`var _old_player = _status.new_connections[_i];`
Which sould be:
`var _old_player = _status.new_disconnections[_i];`

Thanks :)

**Comment by JujuAdams** [comment]
Thank you - fixed.
