### ISSUE TITLE
Cursor won't stop.

### ISSUE THREAD

**Issue by Izsogood** [offalynne/Input#852]
Hello, small issue with the gamepad, the cursor can't stop going up when touching nothing.
The gamepad_axis_value(0, gp_axisrv) = -0.0 and the cursor stop when it is equal to 0 or 0.1
How do I make the cursor stop with a value of 0.1 to -0.1?

**Comment by offalynne** [comment]
Quit Steam

**Comment by Izsogood** [comment]
I tried, nothing changed and the game run on Steam so it's a no go. I come up with this and it seems to work.

if (gamepad_is_connected(0))
{
	if (gamepad_axis_value(0, gp_axisrv) > -0.11 and gamepad_axis_value(0, gp_axisrv) < 0) display_mouse_set(display_mouse_get_x(), display_mouse_get_y()+1)
}

Thank's

**Comment by offalynne** [comment]
Something about your configuration is forcing gamepad axis to drive the mouse. This is not GM or Input related but specific to your configuration. You need to look at your settings for Steam (Gamepad Desktop Configuration) or other software (DS4Win, Betterjoy, whatever) and turn them off.
