### ISSUE TITLE
Recent GM update 2024.2.0.132 caused an issue with Input.

### ISSUE THREAD

**Issue by darthcrawl** [offalynne/Input#856]
I was using Input 5.3.1 and upgraded GM to V.2024.2.0.132 and I got this error.

```
############################################################################################
ERROR in
action number 1
of  Step Event1
for object input_controller_object:

Cannot compare unset variables############################################################################################
gml_Script___tick@anon@2303@__input_class_cursor___input_class_cursor (line 147)
gml_Script_tick@anon@55317@__input_class_player___input_class_player (line 1548)
gml_Script___input_system_tick (line 619)
gml_Object_input_controller_object_Step_1 (line 0)
```

I upgraded input to 6.1.5 and it didn't fix the error, so I made a blank project and dropped Input 6.1.5 into it and still got the error, ruling out everything but Input.
I restored Input back to 5.3.1, The I downgraded GM to V.2023.11.1.129 and Input worked. So I upgraded Input again to the 6.1.5 and it still works.

**Comment by JujuAdams** [comment]
Please upgrade to the [6.2.3 beta](https://github.com/offalynne/Input/releases/tag/6.2.3beta).

**Comment by darthcrawl** [comment]
Thanks. I didn't even know it was available yet.
