### ISSUE TITLE
Combos containing chords fail

### ISSUE THREAD

**Issue by EloiseWilde** [offalynne/Input#858]
The chord's singular verb is considered erroneous input. This could be solved with a complexity check that waits for further input before deeming the combo a success or failure.

A separate issue that stems from this is how to handle similar combos. For example:

Combo 1: A, A
Combo 2: A, J+A

Combo 2 will always fail since A was pressed. My desired behavior would be if J+A is pressed, Combo 2 succeeds and Combo 1 fails due to its lower complexity.

**Comment by offalynne** [comment]
Few misunderstandings here.

Chords loosely evaluate a combination of presses. Combos strictly evaluate an order of inputs. These are separate interfaces that do not interoperate.

Combos are evaluated independently of each other. If you want to introduce a relationship between them across your combo checking, that's left up to your own implementation.
