### ISSUE TITLE
Issue with Button Detection in Beta 2024.400

### ISSUE THREAD

**Issue by nuevocharrua** [offalynne/Input#859]
I am writing to report a problem I've encountered in the Beta 2024.400 version of GameMaker. The issue is related to button detection, which does not seem to function correctly. I have been unable to determine a consistent pattern, but it appears that the issue varies depending on the control used.

**Example working without the library:**
[controller_test_without_lib.zip](https://github.com/offalynne/Input/files/15025622/controller_test_without_lib.zip)

**Example with the library that does not work:**
[controller_test.zip](https://github.com/offalynne/Input/files/15025628/controller_test.zip)

**GM Version:**

- Beta IDE v2024.400.0.543 
- Beta Runtime v2024.400.0.562

**Input Version:**

- 6.1.5

**Comment by offalynne** [comment]
Per README, Input targets LTS. If you can provide 
1. A project without the library to demonstrate what you want to do is actually working in GM Beta
2. Your config/code using Input library that demonstrates the issue
3. Full IDE and Runtime version information 

then we can take a look

**Comment by nuevocharrua** [comment]
Done

**Comment by offalynne** [comment]
Thank you for the example projects. Can you confirm what platforms you are testing, and what gamepads ?

**Comment by nuevocharrua** [comment]
Testing on macOS
- Xbox One Controller
- Dual Shock PS4

**Comment by nuevocharrua** [comment]
I found the problem! On macOS, the buttons have a certain index offset which is fixed on this line:
https://github.com/offalynne/Input/blob/49fdc812f4bb92b6717f5f47b18aee085190bf4e/scripts/__input_class_gamepad/__input_class_gamepad.gml#L247
However, it seems that this offset has changed in the latest version, so the 17 needs to be changed to 28 (an undocumented change by YoYo).

**Comment by offalynne** [comment]
Patched for next release, thank you ! https://github.com/offalynne/Input/commit/6a5cff20931757b817ebe71954ca8784cb42b4f6
