### ISSUE TITLE
The error that occurs when I press the trigger

### ISSUE THREAD

**Issue by mbeytekin** [offalynne/Input#870]
When I try to use it with the Xbox One gamepad and press the right or left trigger, it gives the following error.

############################################################################################
ERROR in
action number 1
of  Step Event1
for object input_controller_object:

Variable <unknown_object>.index(100345, -2147483648) not set before reading it.
 at gml_Script___tick@anon@9391@__input_class_gamepad@__input_class_gamepad (line 296) -                             if (!__INPUT_SILENT) __input_trace("Fully extending XInput trigger scale for gamepad ", index);
############################################################################################
gml_Script___tick@anon@9391@__input_class_gamepad@__input_class_gamepad (line 296)
gml_Script___input_system_tick (line 528) -                 var _sustain_connection = _gamepad.__tick(_connected);
gml_Object_input_controller_object_Step_1 (line 1) - __input_system_tick();

**Comment by mbeytekin** [comment]
when I change :
if (!__INPUT_SILENT) __input_trace("Fully extending XInput trigger scale for gamepad ", index); 
to
// if (!__INPUT_SILENT) __input_trace("Fully extending XInput trigger scale for gamepad ", index);

in '__input_class_gamepad' it works. what is these lines for? Is it important?

**Comment by offalynne** [comment]
Update to the latest release (https://github.com/offalynne/Input/releases/tag/6.2.5)
