### ISSUE TITLE
Check new GMS2.3.3 `mb_side` misbehaviour

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#88]
works: hold side2 (forward) and press side1 (back)
doesn't: hold side1 (back) and press side2 (forward)

confirmed this is independent of Input, will file a bug w YYG

**Comment by JujuAdams** [comment]
"YYG strikes again" 😂

**Comment by offalynne** [comment]
bonked YYG. if it isn't fixed before upstream features leave beta and v4 is meriting release, will investigate a stopgap.

**Comment by offalynne** [comment]
> I have now confirmed the issue and reported it in our bug database.

**Comment by JujuAdams** [comment]
GMS2.3.3 went into stable today - workaround time perhaps

**Comment by offalynne** [comment]
since the alternative is rolling back to our (kind of ugly) fix i'm glad to leave this up to yoyo to (hopefully) fix, simultaneous back+forward mouse button jank shouldn't prove showstopping

**Comment by offalynne** [comment]
Fixed in Runtime 2.3.3.437

**Comment by JujuAdams** [comment]
Miracles do happen after all
