### ISSUE TITLE
Error 404 loop - Documentation

### ISSUE THREAD

**Issue by indieklem** [offalynne/Input#881]
If I get a 404 error on the Input documentation, like this one: [https://offalynne.github.io/Input/#/404](https://offalynne.github.io/Input/#/404)
The logo at the top left of the page will also be a 404 error.
- The url is: [https://offalynne.github.io/](https://offalynne.github.io/)
- Instead of: [https://offalynne.github.io/Input/#/7.0/](https://offalynne.github.io/Input/#/7.0/)

![image](https://github.com/user-attachments/assets/a8843b73-bdc7-4f43-a861-c01d720c5d79)

**Comment by offalynne** [comment]
Unable to reproduce: < https://offalynne.github.io/Input/#/7.0/> works fine for me

**Comment by offalynne** [comment]
Where do you see a link to "https://offalynne.github.io/" ?
The target URL has always been "https://offalynne.github.io/Input"

Edit: The incorrect link on the 404 page is a Docsify bug. What page were you trying to reach that landed you on 404 ?

**Comment by indieklem** [comment]
When I type "input" in my browser I sometimes get an old link "https://offalynne.github.io/Input/#/dummy-hash", this is how I go to the doc of input.
And this is where the 404 url is wrong when I want to go back to the homepage.
