### ISSUE TITLE
Inconsistent detection of gamepad status

### ISSUE THREAD

**Issue by ABNTGeneric** [offalynne/Input#887]
![GAMEMAKER](https://github.com/user-attachments/assets/e0cbe882-719a-44c6-8ecc-15de22cab055)
The function 'input_player_using_gamepad' returns true while the function 'input_player_get_gamepad' still returns -1. This happens when the code is run on the same frame as the async "gamepad connected" event. I'm using standard xInput and PS4 controllers and the function input_player_get_gamepad otherwise returns the proper index.

**Comment by ABNTGeneric** [comment]
Turns out, 'input_player_using_gamepad' does not account for the gamepad being disconnected. It only checks to see if the last connected source _was_ a gamepad. For code like this to work, you must also run a check to see if the source is connected using 'input_player_connected'

**Comment by offalynne** [comment]
Will add a note to the docs to reflect this, thanks for following up with your final findings
