### ISSUE TITLE
input_player_connected not working as expected

### ISSUE THREAD

**Issue by ABNTGeneric** [offalynne/Input#888]
![InputConnectionIssue01](https://github.com/user-attachments/assets/2169296c-4a42-4eb5-899c-838e42ef3f12)
![InputConnectionIssue02](https://github.com/user-attachments/assets/6a6b3c0d-7ccb-45c5-b739-133d6320d09a)
When connecting a new gamepad, my game uses `input_source_set` to assign it to the lowest unconnected player, and it seems to work, except that when attempting to refreshing my game's objects, the information they receive about who's connected doesn't reflect this.

As you can see, the console tells me 'Input: Gamepad 0 connected', and even tells me in player 1's sources that gamepad 0 is in fact connected to player 1. Yet when `input_player_connected(0)` is called, it returns false. I can't use `input_player_get_gamepad` for this because it doesn't tell if the player is actually connected, only that their last assigned source was a gamepad. `input_players_get_status` also fails to reflect changes, as even after a gamepad has been added or removed, its variable `__any_changed` is always 0.

The gamepad works, and functions such as `input_check(<verb>, 0)` work, but in order for my game to work, it needs a consistent way of gathering gamepad information when it changes, not just when a verb is triggered.

**Comment by ABNTGeneric** [comment]
The solution I've settled on for this specific issue is to treat the array length of `input_source_get_array` as a boolean for whether or not the player is connected.

**Comment by offalynne** [comment]
Can you please share a (minimal) code example to demonstrate the issue ?

Edit: `input_players_get_status()` is not meant to reflect changes made by `input_source_set()` within the same frame. I will add a note regarding this to documentation. I suggest reviewing the Multiplayer Guide in the docs: https://offalynne.github.io/Input/#/8.0/Multiplayer-Guide?id=multiplayer-guide
