### ISSUE TITLE
Multi-gamepad input

### ISSUE THREAD

**Issue by JujuAdams** [offalynne/Input#94]
Allow multiple gamepads to pipe input to a single player. This is useful for accessibility (and could enable in-engine pairing of single Joy-Cons if we really wanted to support that).

**Comment by offalynne** [comment]
Resolving this meaningfully seems fraught and unmanageable to me. Would prefer device-mixing to be single-player only as in mixed input (#19).

**Comment by JujuAdams** [comment]
Bindings need to track device index

**Comment by JujuAdams** [comment]
...which is a duplicate of #286
