### ISSUE TITLE
Rebinding wrinkles

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#97]
Rebinding gets stuck in “waiting for release” (state 1) in certain scenarios, most notably with gamepads that have axes resting at nonzero values connected, after keyboard events are missed due to window focus change, and after certain key combinations. This seems to be more of a problem for non-Windows targets but it can exhibit on Windows as well. Needs further testing.

**Comment by JujuAdams** [comment]
Likely the "nothing pressed" function never returning true?

**Comment by JujuAdams** [comment]
I'll tackle this when I get time

**Comment by JujuAdams** [comment]
Added in a timeout feature so that we at the very least don't lock up any games https://github.com/JujuAdams/Input/commit/ee720298745670e6924a7b943d22398c22bd0b28

**Comment by offalynne** [comment]
Currently only exhibiting on Linux

**Comment by offalynne** [comment]
Linux fixed in #117. Bindings show "undefined" in Android but rebinding does appear to do.. something.
