### ISSUE TITLE
Gamepads without a native map incorrectly handled on MacOS

### ISSUE THREAD

**Issue by offalynne** [offalynne/Input#99]
As reported by @diesellaws via Discord, on MacOS, gamepads *without* a native/inbuilt mapping are being handled incorrectly.

I should be able to author a patch myself but in case Juju gets to it first.. ;-]

- Kill https://github.com/JujuAdams/Input/blob/dev/scripts/__input_gamepad_find_in_sdl2_database/__input_gamepad_find_in_sdl2_database.gml#L120-L125

- Flag inbuilt mapping `(gamepad_get_mapping(index) != "") && (gamepad_get_mapping(index) != "no mapping")` here (before wiping)
https://github.com/JujuAdams/Input/blob/dev/scripts/__input_class_gamepad/__input_class_gamepad.gml#L113

- Skip this fix if no inbuilt mapping
https://github.com/JujuAdams/Input/blob/dev/scripts/__input_class_gamepad/__input_class_gamepad.gml#L134-L139

**Comment by JujuAdams** [comment]
1. I can't remember why we're doing this? Maybe left over from when we were feeling more cautious about our ability to appropriately clear GM's internal mapping
2. 👍 
3. GameMaker... I swear...

bonk https://github.com/JujuAdams/Input/commit/b2aed4816163bb7a074be5ba360763c463e707c0

(Please re-test to confirm)

**Comment by offalynne** [comment]
Confirmed fix in https://github.com/JujuAdams/Input/commit/b2aed4816163bb7a074be5ba360763c463e707c0
